/-
Copyright (c) 2026 Kotaro Matsuoka. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Kotaro Matsuoka
-/

import FormalProof4FHE.RLWE.CompactCoverCyclicCompiler

/-!
# Joint scalar compact-cover BGV security game

The public evaluation directory and a bounded batch of symmetric encryption
queries are indexed as one common-secret row family.  The left/right theorem
passes through one uniform transcript, so its only cryptographic terms are two
advantages for the named joint Binary-NTT source problem.  There is no
per-row, circular, or quadratic-KDM assumption in this composition.
-/

open OracleComp

namespace FormalProof4FHE.RLWE.BinaryNTTSecurity.CompactCoverBGVScalarSecurity

open CompactCoverCyclicCompiler

noncomputable section

/-- Public unit/offset pair from which the four stored quadratic-hint elements
are derived coordinatewise. -/
structure CompilerContext (R : Type) [CommRing R] where
  pivot : Rˣ
  offset : R

def compilerContextEquiv (R : Type) [CommRing R] :
    CompilerContext R ≃ Rˣ × R where
  toFun context := (context.pivot, context.offset)
  invFun pair := ⟨pair.1, pair.2⟩
  left_inv context := by cases context; rfl
  right_inv pair := by cases pair; rfl

noncomputable instance instFintypeCompilerContext
    (R : Type) [CommRing R] [Fintype R] : Fintype (CompilerContext R) := by
  letI : Fintype Rˣ := Fintype.ofFinite Rˣ
  exact Fintype.ofEquiv (Rˣ × R) (compilerContextEquiv R).symm

def CompilerContext.hintU {R : Type} [CommRing R]
    (context : CompilerContext R) : R :=
  context.offset + context.offset - context.pivot

def CompilerContext.hintV {R : Type} [CommRing R]
    (context : CompilerContext R) : R :=
  context.pivot * context.offset - context.offset * context.offset

/-- The exact quadratic-hint relation generated by TFHEpp from an idempotent
Binary-NTT witness. -/
theorem CompilerContext.targetSecret_square {R : Type} [CommRing R]
    (context : CompilerContext R) (witness : R)
    (idempotent : witness * witness = witness) :
    targetSecret context.pivot context.offset witness ^ 2 =
      context.hintU * targetSecret context.pivot context.offset witness +
        context.hintV := by
  simp only [targetSecret, CompilerContext.hintU, CompilerContext.hintV,
    pow_two]
  apply sub_eq_zero.mp
  calc
    _ = (context.pivot : R) ^ 2 * (witness * witness - witness) := by ring
    _ = 0 := by rw [idempotent, sub_self, mul_zero]

/-- Rows physically stored in the scalar N=65536 evaluation directory. -/
inductive EvaluationRow where
  | phaseLift : Fin 2 → EvaluationRow
  | traceEarly : Fin 8 → Fin 23 → EvaluationRow
  | traceLate : Fin 8 → Fin 23 → EvaluationRow
  deriving DecidableEq, Fintype

@[simp] theorem evaluationRow_card : Fintype.card EvaluationRow = 370 := by
  native_decide

/-- One row family contains the fixed directory and every encryption sample
made available to a bounded-query symmetric adversary. -/
inductive ScalarRow (queries : ℕ) where
  | evaluation : EvaluationRow → ScalarRow queries
  | encryption : Fin queries → ScalarRow queries
  deriving DecidableEq, Fintype

def scalarRowEquiv (queries : ℕ) :
    ScalarRow queries ≃ EvaluationRow ⊕ Fin queries where
  toFun
    | .evaluation row => Sum.inl row
    | .encryption query => Sum.inr query
  invFun
    | .inl row => .evaluation row
    | .inr query => .encryption query
  left_inv row := by cases row <;> rfl
  right_inv row := by cases row <;> rfl

@[simp] theorem scalarRow_card (queries : ℕ) :
    Fintype.card (ScalarRow queries) = 370 + queries := by
  rw [Fintype.card_congr (scalarRowEquiv queries), Fintype.card_sum]
  simp

/-- Late trace rows are stored after one RNS drop; all other directory rows
are represented at the full level. -/
def EvaluationRow.activeLimbs : EvaluationRow → ℕ
  | .traceLate _ _ => 19
  | _ => 20

theorem EvaluationRow.activeLimbs_eq_nineteen_iff (row : EvaluationRow) :
    row.activeLimbs = 19 ↔ ∃ stage digit, row = .traceLate stage digit := by
  cases row <;> simp [EvaluationRow.activeLimbs]

abbrev Transcript (queries : ℕ) (R : Type) := ScalarRow queries → R × R

/-- Evaluation-key constants are shared between the challenge sides; only the
chosen encryption messages may differ. -/
structure ChallengeConstants (queries : ℕ) (R : Type) where
  evaluation : EvaluationRow → R
  leftMessage : Fin queries → R
  rightMessage : Fin queries → R

def ChallengeConstants.leftTable {queries : ℕ} {R : Type}
    (constants : ChallengeConstants queries R) : ScalarRow queries → R
  | .evaluation row => constants.evaluation row
  | .encryption query => constants.leftMessage query

def ChallengeConstants.rightTable {queries : ℕ} {R : Type}
    (constants : ChallengeConstants queries R) : ScalarRow queries → R
  | .evaluation row => constants.evaluation row
  | .encryption query => constants.rightMessage query

@[simp] theorem ChallengeConstants.tables_agree_on_evaluation
    {queries : ℕ} {R : Type} (constants : ChallengeConstants queries R)
    (row : EvaluationRow) :
    constants.leftTable (.evaluation row) =
      constants.rightTable (.evaluation row) := rfl

/-- The exact joint Binary-NTT source problem.  Its real endpoint may use the
concrete mixed CBD/RNS row laws; its random endpoint is the complete uniform
row table. -/
def jointSourceProblem (queries : ℕ) (R : Type)
    [Fintype R] [SampleableType R] [SampleableType (Transcript queries R)]
    (realSource : ProbComp (Transcript queries R)) :
    DecisionProblem (Transcript queries R) where
  real := realSource
  random := $ᵗ (Transcript queries R)

/-- Public compilation of the common-witness source into the advertised-key
evaluation directory and encryption batch. -/
def compiledProblem (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (pivot : Rˣ) (offset : R)
    (message : ScalarRow queries → WitnessAffine R)
    (publicConstant : ScalarRow queries → R)
    (realSource : ProbComp (Transcript queries R)) :
    DecisionProblem (Transcript queries R) where
  real := compilerBatch pivot offset message publicConstant <$> realSource
  random := $ᵗ (Transcript queries R)

/-- The complete compilation is one exact reduction.  In particular, its
uniform endpoint is proved jointly rather than by a hybrid over rows. -/
def compiledReduction (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (pivot : Rˣ) (offset : R)
    (message : ScalarRow queries → WitnessAffine R)
    (publicConstant : ScalarRow queries → R)
    (realSource : ProbComp (Transcript queries R)) :
    ExactMapReduction (jointSourceProblem queries R realSource)
      (compiledProblem queries R pivot offset message publicConstant realSource) where
  transform := compilerBatch pivot offset message publicConstant
  realLaw := by simp [jointSourceProblem, compiledProblem]
  randomLaw := by
    simpa [jointSourceProblem, compiledProblem] using
      compilerBatch_uniform_evalDist pivot offset message publicConstant

/-- A symmetric left/right view uses the same evaluation-key messages and may
differ only in public constants attached to the encryption-query rows. -/
def leftRightProblem (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (pivot : Rˣ) (offset : R)
    (message : ScalarRow queries → WitnessAffine R)
    (leftConstant rightConstant : ScalarRow queries → R)
    (realSource : ProbComp (Transcript queries R)) :
    DecisionProblem (Transcript queries R) where
  real := (compiledProblem queries R pivot offset message leftConstant realSource).real
  random := (compiledProblem queries R pivot offset message rightConstant realSource).real

/-- **Concrete joint IND-CPA composition.**  The left/right gap is at most the
sum of the two joint Binary-NTT source gaps.  The pullbacks are explicit and
share the exact fixed evaluation directory; no circular-security term occurs. -/
theorem leftRight_advantage_le_two_source
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (pivot : Rˣ) (offset : R)
    (message : ScalarRow queries → WitnessAffine R)
    (leftConstant rightConstant : ScalarRow queries → R)
    (realSource : ProbComp (Transcript queries R))
    (distinguisher : Distinguisher (Transcript queries R)) :
    advantage (leftRightProblem queries R pivot offset message
        leftConstant rightConstant realSource) distinguisher ≤
      advantage (jointSourceProblem queries R realSource)
        ((compiledReduction queries R pivot offset message leftConstant
          realSource).pullback distinguisher) +
      advantage (jointSourceProblem queries R realSource)
        ((compiledReduction queries R pivot offset message rightConstant
          realSource).pullback distinguisher) := by
  let left := compiledProblem queries R pivot offset message leftConstant realSource
  let right := compiledProblem queries R pivot offset message rightConstant realSource
  have triangle := ProbComp.boolDistAdvantage_triangle
    (left.real >>= distinguisher) (left.random >>= distinguisher)
    (right.real >>= distinguisher)
  have middle :
      (left.random >>= distinguisher).boolDistAdvantage
        (right.real >>= distinguisher) =
      (right.real >>= distinguisher).boolDistAdvantage
        (right.random >>= distinguisher) := by
    change (($ᵗ (Transcript queries R)) >>= distinguisher).boolDistAdvantage
        (right.real >>= distinguisher) =
      (right.real >>= distinguisher).boolDistAdvantage
        (($ᵗ (Transcript queries R)) >>= distinguisher)
    unfold ProbComp.boolDistAdvantage
    rw [abs_sub_comm]
  rw [middle] at triangle
  have leftEquality := (compiledReduction queries R pivot offset message
    leftConstant realSource).advantage_pullback distinguisher
  have rightEquality := (compiledReduction queries R pivot offset message
    rightConstant realSource).advantage_pullback distinguisher
  change (left.real >>= distinguisher).boolDistAdvantage
      (right.real >>= distinguisher) ≤ _
  calc
    _ ≤ advantage left distinguisher + advantage right distinguisher := triangle
    _ = _ := by rw [← leftEquality, ← rightEquality]

/-- If the allowed Binary-NTT class is closed under both public compiler
pullbacks, an `epsilon` source bound gives a `2*epsilon` symmetric IND-CPA
bound. -/
theorem leftRight_hardAgainst
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (pivot : Rˣ) (offset : R)
    (message : ScalarRow queries → WitnessAffine R)
    (leftConstant rightConstant : ScalarRow queries → R)
    (realSource : ProbComp (Transcript queries R))
    (sourceAllowed : Distinguisher (Transcript queries R) → Prop)
    (targetAllowed : Distinguisher (Transcript queries R) → Prop)
    (epsilon : ℝ)
    (closedLeft : ∀ distinguisher, targetAllowed distinguisher →
      sourceAllowed ((compiledReduction queries R pivot offset message
        leftConstant realSource).pullback distinguisher))
    (closedRight : ∀ distinguisher, targetAllowed distinguisher →
      sourceAllowed ((compiledReduction queries R pivot offset message
        rightConstant realSource).pullback distinguisher))
    (sourceHard : HardAgainst (jointSourceProblem queries R realSource)
      sourceAllowed epsilon) :
    HardAgainst (leftRightProblem queries R pivot offset message
      leftConstant rightConstant realSource) targetAllowed (2 * epsilon) := by
  intro distinguisher allowed
  have bound := leftRight_advantage_le_two_source queries R pivot offset message
    leftConstant rightConstant realSource distinguisher
  have leftBound := sourceHard _ (closedLeft distinguisher allowed)
  have rightBound := sourceHard _ (closedRight distinguisher allowed)
  linarith

/-- Named symmetric IND-CPA corollary: evaluation material is literally the
same on both sides, while every chosen encryption message may change. -/
theorem symmetricINDCPA_advantage_le_two_source
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (pivot : Rˣ) (offset : R)
    (message : ScalarRow queries → WitnessAffine R)
    (constants : ChallengeConstants queries R)
    (realSource : ProbComp (Transcript queries R))
    (distinguisher : Distinguisher (Transcript queries R)) :
    advantage (leftRightProblem queries R pivot offset message
        constants.leftTable constants.rightTable realSource) distinguisher ≤
      advantage (jointSourceProblem queries R realSource)
        ((compiledReduction queries R pivot offset message constants.leftTable
          realSource).pullback distinguisher) +
      advantage (jointSourceProblem queries R realSource)
        ((compiledReduction queries R pivot offset message constants.rightTable
          realSource).pullback distinguisher) :=
  leftRight_advantage_le_two_source queries R pivot offset message
    constants.leftTable constants.rightTable realSource distinguisher

/-! ## Sampled public context -/

abbrev ContextualView (queries : ℕ) (R : Type) [CommRing R] :=
  CompilerContext R × Transcript queries R

/-- Explicit common-secret Binary-NTT rows.  The error table is sampled as one
object, so it may encode coherent RNS residues and different laws at different
row tags without pretending that the limbs are independent. -/
def commonSecretRows {queries : ℕ} {R : Type} [CommRing R]
    (witness : R) (masks errors : ScalarRow queries → R) :
    Transcript queries R :=
  fun row => (masks row, masks row * witness + errors row)

@[simp] theorem commonSecretRows_phase {queries : ℕ} {R : Type} [CommRing R]
    (witness : R) (masks errors : ScalarRow queries → R)
    (row : ScalarRow queries) :
    (commonSecretRows witness masks errors row).2 -
        (commonSecretRows witness masks errors row).1 * witness = errors row := by
  simp [commonSecretRows]

/-- The concrete joint Binary-NTT premise used by the sampled-context theorem:
sample the public unit/offset context and one idempotent witness, then one
uniform mask table and one coherent mixed-error table. -/
def commonSecretSource (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (ScalarRow queries → R)]
    (contextWitnessSampler : ProbComp (CompilerContext R × R))
    (errorSampler : ProbComp (ScalarRow queries → R)) :
    ProbComp (ContextualView queries R) := do
  let contextWitness ← contextWitnessSampler
  let masks ← $ᵗ (ScalarRow queries → R)
  let errors ← errorSampler
  return (contextWitness.1,
    commonSecretRows contextWitness.2 masks errors)

def contextualRandomRows (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (source : ProbComp (ContextualView queries R)) :
    ProbComp (ContextualView queries R) := do
  let view ← source
  let rows ← $ᵗ (Transcript queries R)
  return (view.1, rows)

def contextualCompiler (queries : ℕ) (R : Type) [CommRing R]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (publicConstant : CompilerContext R → ScalarRow queries → R)
    (view : ContextualView queries R) : ContextualView queries R :=
  (view.1, compilerBatch view.1.pivot view.1.offset
    (message view.1) (publicConstant view.1) view.2)

theorem contextualCompiler_randomRows
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (publicConstant : CompilerContext R → ScalarRow queries → R)
    (source : ProbComp (ContextualView queries R)) :
    evalDist (contextualCompiler queries R message publicConstant <$>
      contextualRandomRows queries R source) =
      evalDist (contextualRandomRows queries R source) := by
  simp only [contextualRandomRows, contextualCompiler, map_eq_bind_pure_comp,
    bind_assoc, Function.comp_apply, pure_bind]
  refine evalDist_bind_congr' source fun view => ?_
  have uniformLaw := compilerBatch_uniform_evalDist view.1.pivot view.1.offset
    (message view.1) (publicConstant view.1)
  simpa only [map_eq_bind_pure_comp, bind_assoc, pure_bind,
    Function.comp_apply] using
    (FormalProof4FHE.SharedRandomness.evalDist_bind_eq_of_evalDist_eq
      uniformLaw (fun rows => pure (view.1, rows)))

def contextualSourceProblem (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (realSource : ProbComp (ContextualView queries R)) :
    DecisionProblem (ContextualView queries R) where
  real := realSource
  random := contextualRandomRows queries R realSource

def commonSecretBinaryNTTProblem (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (ScalarRow queries → R)]
    [SampleableType (Transcript queries R)]
    (contextWitnessSampler : ProbComp (CompilerContext R × R))
    (errorSampler : ProbComp (ScalarRow queries → R)) :
    DecisionProblem (ContextualView queries R) :=
  contextualSourceProblem queries R
    (commonSecretSource queries R contextWitnessSampler errorSampler)

/-- Proof-carrying Binary-NTT source specification.  The witness condition is
the formal distinction between Binary-NTT RLWE and an arbitrary common-secret
row distribution. -/
structure BinaryNTTSourceSpec (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (ScalarRow queries → R)] where
  contextWitnessSampler : ProbComp (CompilerContext R × R)
  errorSampler : ProbComp (ScalarRow queries → R)
  witness_idempotent : ∀ sample,
    sample ∈ support contextWitnessSampler → sample.2 ^ 2 = sample.2
  source_neverFails : NeverFail
    (commonSecretSource queries R contextWitnessSampler errorSampler)

def BinaryNTTSourceSpec.problem (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (ScalarRow queries → R)]
    [SampleableType (Transcript queries R)]
    (source : BinaryNTTSourceSpec queries R) :
    DecisionProblem (ContextualView queries R) :=
  commonSecretBinaryNTTProblem queries R source.contextWitnessSampler
    source.errorSampler

def contextualCompiledProblem (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (publicConstant : CompilerContext R → ScalarRow queries → R)
    (realSource : ProbComp (ContextualView queries R)) :
    DecisionProblem (ContextualView queries R) where
  real := contextualCompiler queries R message publicConstant <$> realSource
  random := contextualRandomRows queries R realSource

/-- Sampling and publishing the product-unit pivot, offset, and derived
quadratic hint does not change the exact uniform-row transport. -/
def contextualCompiledReduction
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (publicConstant : CompilerContext R → ScalarRow queries → R)
    (realSource : ProbComp (ContextualView queries R)) :
    ExactMapReduction (contextualSourceProblem queries R realSource)
      (contextualCompiledProblem queries R message publicConstant realSource) where
  transform := contextualCompiler queries R message publicConstant
  realLaw := by simp [contextualSourceProblem, contextualCompiledProblem]
  randomLaw := by
    simpa [contextualSourceProblem, contextualCompiledProblem,
      map_eq_bind_pure_comp] using
      contextualCompiler_randomRows queries R message publicConstant realSource

def contextualLeftRightProblem
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (constants : CompilerContext R → ChallengeConstants queries R)
    (realSource : ProbComp (ContextualView queries R)) :
    DecisionProblem (ContextualView queries R) where
  real := (contextualCompiledProblem queries R message
    (fun context => (constants context).leftTable) realSource).real
  random := (contextualCompiledProblem queries R message
    (fun context => (constants context).rightTable) realSource).real

/-- Final sampled-context symmetric IND-CPA composition.  The context contains
the product-unit pivot and offset and therefore also determines the public
quadratic hint. -/
theorem contextualINDCPA_advantage_le_two_source
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (Transcript queries R)]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (constants : CompilerContext R → ChallengeConstants queries R)
    (realSource : ProbComp (ContextualView queries R))
    (distinguisher : Distinguisher (ContextualView queries R)) :
    advantage (contextualLeftRightProblem queries R message constants realSource)
        distinguisher ≤
      advantage (contextualSourceProblem queries R realSource)
        ((contextualCompiledReduction queries R message
          (fun context => (constants context).leftTable) realSource).pullback
            distinguisher) +
      advantage (contextualSourceProblem queries R realSource)
        ((contextualCompiledReduction queries R message
          (fun context => (constants context).rightTable) realSource).pullback
            distinguisher) := by
  let left := contextualCompiledProblem queries R message
    (fun context => (constants context).leftTable) realSource
  let right := contextualCompiledProblem queries R message
    (fun context => (constants context).rightTable) realSource
  have triangle := ProbComp.boolDistAdvantage_triangle
    (left.real >>= distinguisher) (left.random >>= distinguisher)
    (right.real >>= distinguisher)
  have middle :
      (left.random >>= distinguisher).boolDistAdvantage
        (right.real >>= distinguisher) =
      (right.real >>= distinguisher).boolDistAdvantage
        (right.random >>= distinguisher) := by
    change (contextualRandomRows queries R realSource >>= distinguisher).boolDistAdvantage
        (right.real >>= distinguisher) =
      (right.real >>= distinguisher).boolDistAdvantage
        (contextualRandomRows queries R realSource >>= distinguisher)
    unfold ProbComp.boolDistAdvantage
    rw [abs_sub_comm]
  rw [middle] at triangle
  have leftEquality := (contextualCompiledReduction queries R message
    (fun context => (constants context).leftTable) realSource).advantage_pullback
      distinguisher
  have rightEquality := (contextualCompiledReduction queries R message
    (fun context => (constants context).rightTable) realSource).advantage_pullback
      distinguisher
  change (left.real >>= distinguisher).boolDistAdvantage
      (right.real >>= distinguisher) ≤ _
  calc
    _ ≤ advantage left distinguisher + advantage right distinguisher := triangle
    _ = _ := by rw [← leftEquality, ← rightEquality]

/-- Fully named source specialization.  All implementation-specific choices
are now localized to the context/witness and coherent error samplers. -/
theorem contextualINDCPA_le_commonSecretBinaryNTT
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (ScalarRow queries → R)]
    [SampleableType (Transcript queries R)]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (constants : CompilerContext R → ChallengeConstants queries R)
    (contextWitnessSampler : ProbComp (CompilerContext R × R))
    (errorSampler : ProbComp (ScalarRow queries → R))
    (distinguisher : Distinguisher (ContextualView queries R)) :
    advantage (contextualLeftRightProblem queries R message constants
        (commonSecretSource queries R contextWitnessSampler errorSampler))
        distinguisher ≤
      advantage (commonSecretBinaryNTTProblem queries R contextWitnessSampler
        errorSampler)
        ((contextualCompiledReduction queries R message
          (fun context => (constants context).leftTable)
          (commonSecretSource queries R contextWitnessSampler errorSampler)).pullback
            distinguisher) +
      advantage (commonSecretBinaryNTTProblem queries R contextWitnessSampler
        errorSampler)
        ((contextualCompiledReduction queries R message
          (fun context => (constants context).rightTable)
          (commonSecretSource queries R contextWitnessSampler errorSampler)).pullback
            distinguisher) :=
  contextualINDCPA_advantage_le_two_source queries R message constants
    (commonSecretSource queries R contextWitnessSampler errorSampler) distinguisher

theorem contextualINDCPA_le_binaryNTTSourceSpec
    (queries : ℕ) (R : Type)
    [CommRing R] [Fintype R] [SampleableType R]
    [SampleableType (ScalarRow queries → R)]
    [SampleableType (Transcript queries R)]
    (message : CompilerContext R → ScalarRow queries → WitnessAffine R)
    (constants : CompilerContext R → ChallengeConstants queries R)
    (source : BinaryNTTSourceSpec queries R)
    (distinguisher : Distinguisher (ContextualView queries R)) :
    advantage (contextualLeftRightProblem queries R message constants
        (commonSecretSource queries R source.contextWitnessSampler
          source.errorSampler)) distinguisher ≤
      advantage (source.problem queries R)
        ((contextualCompiledReduction queries R message
          (fun context => (constants context).leftTable)
          (commonSecretSource queries R source.contextWitnessSampler
            source.errorSampler)).pullback distinguisher) +
      advantage (source.problem queries R)
        ((contextualCompiledReduction queries R message
          (fun context => (constants context).rightTable)
          (commonSecretSource queries R source.contextWitnessSampler
            source.errorSampler)).pullback distinguisher) :=
  contextualINDCPA_le_commonSecretBinaryNTT queries R message constants
    source.contextWitnessSampler source.errorSampler distinguisher

end

end FormalProof4FHE.RLWE.BinaryNTTSecurity.CompactCoverBGVScalarSecurity
