/-
Copyright (c) 2026 Kotaro Matsuoka. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Kotaro Matsuoka
-/

import FormalProof4FHE.Probability.ConditionalCollision
import FormalProof4FHE.RLWE.PowerOfTwoCyclotomic
import FormalProof4FHE.RLWE.QuadraticKDM
import FormalProof4FHE.RLWE.RingRegev

/-!
# Statistical quadratic KDM security at power-of-two moduli

This file formalizes the finite collision argument of
`power_of_two_quadratic_kdm_statistical.tex`.  The source distribution is presented by a
uniform finite random tape.  This is the exact representation used by executable finite
samplers, and it permits the conditional-copy calculation to be stated without division by
zero on leakage values outside the support.

The main finite-ring theorem proves that every ideal-compatible affine message has the same
conditional collision bound.  Quadratic messages `g * s^2` and the masked HNF messages
`g * (s - t)^2` are then instances.  A separate finite-chain-ring certificate records precisely
the ramification facts needed to rewrite the generic principal-ideal expression as the
`2^(ell * val)` expression from the paper.  The companion module
`PowerOfTwoCyclotomicChainRing` constructs that certificate for the literal semantic quotient
`ZMod (2^kappa)[X] / (X^(2^r) + 1)` rather than assuming total ramification.
-/

open BigOperators OracleComp

namespace FormalProof4FHE.RLWE.PowerOfTwoQuadraticKDMStatistical

noncomputable section

/-! ## Multiplication fibers and principal ideals -/

/-- Additive multiplication by a fixed ring element.  Its range is the principal ideal used in
the collision formula. -/
def rightMulAddHom {R : Type} [CommRing R] (difference : R) : R →+ R where
  toFun value := value * difference
  map_zero' := zero_mul difference
  map_add' left right := add_mul left right difference

@[simp]
theorem rightMulAddHom_apply {R : Type} [CommRing R]
    (difference value : R) :
    rightMulAddHom difference value = value * difference := rfl

/-- Membership in the principal ideal generated by `difference`, represented as membership in
the range of multiplication by `difference`. -/
def InPrincipalIdeal {R : Type} [CommRing R] (difference value : R) : Prop :=
  value ∈ (rightMulAddHom difference).range

/-- Finite principal-ideal membership is decidable.  The implementation is proof-only; concrete
parameter code may use a faster ring-specific decision procedure. -/
noncomputable instance instDecidableInPrincipalIdeal
    {R : Type} [CommRing R] [Fintype R]
    (difference value : R) : Decidable (InPrincipalIdeal difference value) :=
  Classical.propDecidable _

theorem inPrincipalIdeal_iff_exists {R : Type} [CommRing R]
    (difference value : R) :
    InPrincipalIdeal difference value ↔ ∃ multiplier, multiplier * difference = value := by
  rfl

@[simp]
theorem zero_inPrincipalIdeal {R : Type} [CommRing R] (difference : R) :
    InPrincipalIdeal difference 0 := by
  exact ⟨0, by simp⟩

theorem neg_inPrincipalIdeal_iff {R : Type} [CommRing R]
    (difference value : R) :
    InPrincipalIdeal difference (-value) ↔ InPrincipalIdeal difference value := by
  constructor
  · rintro ⟨multiplier, hmultiplier⟩
    refine ⟨-multiplier, ?_⟩
    change (-multiplier) * difference = value
    change multiplier * difference = -value at hmultiplier
    rw [neg_mul, hmultiplier, neg_neg]
  · rintro ⟨multiplier, hmultiplier⟩
    refine ⟨-multiplier, ?_⟩
    change (-multiplier) * difference = -value
    change multiplier * difference = value at hmultiplier
    rw [neg_mul, hmultiplier]

/-- The real collision weight of one row: reciprocal image size on a solvable multiplication
fiber and zero otherwise, scaled by `|R|` so that it is also the fiber cardinality. -/
noncomputable def principalFiberWeight
    {R : Type} [CommRing R] [Fintype R]
    (difference target : R) : ℝ := by
  classical
  exact if InPrincipalIdeal difference target then
    (Fintype.card R : ℝ) /
      Fintype.card (rightMulAddHom difference).range
  else 0

/-- Exact size of an arbitrary multiplication-map fiber.  Empty fibers contribute zero; every
nonempty fiber has `|R| / |difference * R|` elements. -/
theorem rightMulFiberCount
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (difference target : R) :
    (∑ value : R, if value * difference = target then (1 : ℝ) else 0) =
      principalFiberWeight difference target := by
  classical
  unfold principalFiberWeight
  by_cases htarget : InPrincipalIdeal difference target
  · rw [if_pos htarget]
    have hzero : (0 : R) ∈ Set.range (rightMulAddHom difference) :=
      ⟨0, map_zero (rightMulAddHom difference)⟩
    have hfiber := AddMonoidHom.card_fiber_eq_of_mem_range
      (rightMulAddHom difference) htarget hzero
    have hcountTarget :
        (∑ value : R, if rightMulAddHom difference value = target then
            (1 : ℝ) else 0) =
          ((Finset.univ.filter fun value : R ↦
            rightMulAddHom difference value = target).card : ℝ) := by
      simp only [Finset.sum_boole]
    rw [show (∑ value : R, if value * difference = target then (1 : ℝ) else 0) =
        ∑ value : R, if rightMulAddHom difference value = target then
          (1 : ℝ) else 0 by rfl,
      hcountTarget, hfiber]
    have hkernel :=
      FormalProof4FHE.ConditionalCollision.zeroFiberCount_addHom_eq_card_div
        (rightMulAddHom difference).rangeRestrict
        (AddMonoidHom.rangeRestrict_surjective (rightMulAddHom difference))
    simpa [Subtype.ext_iff] using hkernel
  · rw [if_neg htarget]
    apply Finset.sum_eq_zero
    intro value _
    rw [if_neg]
    intro heq
    exact htarget ⟨value, heq⟩

@[simp]
theorem principalFiberWeight_neg_target
    {R : Type} [CommRing R] [Fintype R]
    (difference target : R) :
    principalFiberWeight difference (-target) =
      principalFiberWeight difference target := by
  classical
  unfold principalFiberWeight
  rw [if_congr (neg_inPrincipalIdeal_iff difference target) rfl rfl]

/-- Indicator sums over a finite function space factor coordinatewise. -/
theorem sum_pi_indicator_eq_prod
    {Row R : Type} [Fintype Row] [DecidableEq Row]
    [Fintype R] [DecidableEq R]
    (predicate : Row → R → Prop) [∀ row, DecidablePred (predicate row)] :
    (∑ values : Row → R,
        if ∀ row, predicate row (values row) then (1 : ℝ) else 0) =
      ∏ row : Row,
        ∑ value : R, if predicate row value then (1 : ℝ) else 0 := by
  classical
  have hcard := Fintype.card_congr
    (Equiv.subtypePiEquivPi
      (p := fun row value ↦ predicate row value))
  have hcoordinate (row : Row) :
      (∑ value : R, if predicate row value then (1 : ℝ) else 0) =
        (Fintype.card {value : R // predicate row value} : ℝ) :=
    FormalProof4FHE.ConditionalCollision.indicatorSum_eq_card_subtype _
  calc
    (∑ values : Row → R,
        if ∀ row, predicate row (values row) then (1 : ℝ) else 0) =
        (Fintype.card {values : Row → R //
          ∀ row, predicate row (values row)} : ℝ) :=
      FormalProof4FHE.ConditionalCollision.indicatorSum_eq_card_subtype _
    _ = (Fintype.card ((row : Row) →
          {value : R // predicate row value}) : ℝ) := by
      exact_mod_cast hcard
    _ = ((∏ row : Row,
          Fintype.card {value : R // predicate row value}) : ℕ) := by
      rw [Fintype.card_pi]
    _ = ∏ row : Row,
          (Fintype.card {value : R // predicate row value} : ℝ) := by
      exact Nat.cast_prod _ _
    _ = ∏ row : Row,
          ∑ value : R, if predicate row value then (1 : ℝ) else 0 := by
      apply Finset.prod_congr rfl
      intro row _
      exact (hcoordinate row).symm

/-- If a transcript retains its mask, a collision of two complete transcripts first forces the
two masks to be equal. -/
theorem transcriptPairCollisionCount_eq_singleMask
    {R Row : Type} [Fintype R] [DecidableEq R]
    [Fintype Row] [DecidableEq Row]
    (leftBody rightBody : (Row → R) → (Row → R)) :
    (∑ leftMask : Row → R, ∑ rightMask : Row → R,
      if (leftMask, leftBody leftMask) = (rightMask, rightBody rightMask)
      then (1 : ℝ) else 0) =
    ∑ mask : Row → R,
      if leftBody mask = rightBody mask then (1 : ℝ) else 0 := by
  classical
  apply Finset.sum_congr rfl
  intro leftMask _
  rw [Finset.sum_eq_single leftMask]
  · simp
  · intro rightMask _ hne
    simp [hne.symm]
  · simp

/-! ## Ideal-compatible affine rows -/

/-- Public messages indexed by leakage and row. -/
abbrev MessageFamily (R Side Row : Type) := Side → Row → R → R

/-- A message family is ideal-compatible when every same-leakage message difference lies in the
principal ideal generated by the corresponding secret difference. -/
def IdealCompatible {R Side Row : Type} [CommRing R]
    (message : MessageFamily R Side Row) : Prop :=
  ∀ leakage row leftSecret rightSecret,
    InPrincipalIdeal (leftSecret - rightSecret)
      (message leakage row leftSecret - message leakage row rightSecret)

/-- The zero-message family is ideal-compatible. -/
theorem idealCompatible_zero {R Side Row : Type} [CommRing R] :
    IdealCompatible (fun (_leakage : Side) (_row : Row) (_secret : R) ↦ 0) := by
  intro leakage row leftSecret rightSecret
  simp only [sub_self]
  exact zero_inPrincipalIdeal _

/-- Quadratic KDM messages are ideal-compatible over every commutative ring. -/
theorem idealCompatible_quadratic {R Side Row : Type} [CommRing R]
    (weight : Row → R) :
    IdealCompatible
      (fun (_leakage : Side) row secret ↦ weight row * secret ^ 2) := by
  intro leakage row leftSecret rightSecret
  rw [inPrincipalIdeal_iff_exists]
  refine ⟨weight row * (leftSecret + rightSecret), ?_⟩
  ring

/-- The proof-only HNF mask produces another ideal-compatible quadratic family. -/
theorem idealCompatible_maskedQuadratic {R Side Row : Type} [CommRing R]
    (weight : Row → R) (mask : Side → R) :
    IdealCompatible
      (fun leakage row secret ↦ weight row * (secret - mask leakage) ^ 2) := by
  intro leakage row leftSecret rightSecret
  rw [inPrincipalIdeal_iff_exists]
  refine ⟨weight row *
      (leftSecret + rightSecret - 2 * mask leakage), ?_⟩
  ring

/-- Body vector of an affine KDM transcript generated from one source tape and one public mask. -/
def affineBody {R Seed Side Row : Type} [CommRing R]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (seed : Seed) (publicMask : Row → R) : Row → R :=
  fun row ↦ publicMask row * secret seed +
    message (leakage seed) row (secret seed) + error seed row

/-- Complete affine transcript, including the public mask. -/
def affineTranscript {R Seed Side Row : Type} [CommRing R]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (seed : Seed) (publicMask : Row → R) :
    QuadraticKDM.TargetTranscript R Row :=
  (publicMask, affineBody secret error leakage message seed publicMask)

/-- The real joint experiment as a deterministic image of a uniform source-and-mask tape. -/
def affineJointSampler {R Seed Side Row : Type} [CommRing R]
    [SampleableType (Seed × (Row → R))]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row) :
    ProbComp (Side × QuadraticKDM.TargetTranscript R Row) :=
  FormalProof4FHE.ConditionalCollision.uniformJointImage
    (fun input : Seed × (Row → R) ↦ leakage input.1)
    (fun input ↦ affineTranscript secret error leakage message input.1 input.2)

/-- The ideal experiment retains the exact leakage marginal and refreshes the complete pair of
row vectors uniformly. -/
def affineIdealSampler {R Seed Side Row : Type}
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (leakage : Seed → Side) :
    ProbComp (Side × QuadraticKDM.TargetTranscript R Row) :=
  FormalProof4FHE.ConditionalCollision.uniformSideIndependentOutput
    (Output := QuadraticKDM.TargetTranscript R Row)
    (fun input : Seed × (Row → R) ↦ leakage input.1)

/-! ## Exact collision accounting -/

/-- The multiplication-fiber contribution of one row for a pair of source tapes. -/
noncomputable def rowIdealCollisionWeight
    {R Seed Row : Type} [CommRing R] [Fintype R]
    (secret : Seed → R) (error : Seed → Row → R)
    (left right : Seed) (row : Row) : ℝ :=
  principalFiberWeight (secret left - secret right)
    (error left row - error right row)

/-- Product of the independent public-mask fiber counts across all rows. -/
noncomputable def pairIdealCollisionWeight
    {R Seed Row : Type} [CommRing R] [Fintype R] [Fintype Row]
    (secret : Seed → R) (error : Seed → Row → R)
    (left right : Seed) : ℝ :=
  ∏ row : Row, rowIdealCollisionWeight secret error left right row

theorem principalMembership_collisionTarget_iff
    {R : Type} [CommRing R]
    (difference messageDifference errorDifference : R)
    (hmessage : InPrincipalIdeal difference messageDifference) :
    InPrincipalIdeal difference (-(messageDifference + errorDifference)) ↔
      InPrincipalIdeal difference errorDifference := by
  let ideal := (rightMulAddHom difference).range
  constructor
  · intro htarget
    have hsum : messageDifference + errorDifference ∈ ideal := by
      have := ideal.neg_mem htarget
      simpa [ideal] using this
    change errorDifference ∈ ideal
    simpa [add_comm] using ideal.sub_mem hsum hmessage
  · intro herror
    have hsum : messageDifference + errorDifference ∈ ideal :=
      ideal.add_mem hmessage herror
    exact ideal.neg_mem hsum

theorem affineBody_row_eq_iff
    {R Seed Side Row : Type} [CommRing R]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (left right : Seed) (mask : Row → R) (row : Row)
    (hsame : leakage left = leakage right) :
    affineBody secret error leakage message left mask row =
        affineBody secret error leakage message right mask row ↔
      mask row * (secret left - secret right) =
        -((message (leakage left) row (secret left) -
            message (leakage left) row (secret right)) +
          (error left row - error right row)) := by
  unfold affineBody
  rw [hsame]
  constructor <;> intro h <;> linear_combination h

/-- Exact one-row mask count.  Ideal compatibility removes the message term from the result. -/
theorem affineRowMaskCollisionCount
    {R Seed Side Row : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (hcompatible : IdealCompatible message)
    (left right : Seed) (row : Row)
    (hsame : leakage left = leakage right) :
    (∑ mask : R,
      if mask * secret left +
            message (leakage left) row (secret left) + error left row =
          mask * secret right +
            message (leakage right) row (secret right) + error right row
      then (1 : ℝ) else 0) =
      rowIdealCollisionWeight secret error left right row := by
  classical
  let difference := secret left - secret right
  let messageDifference :=
    message (leakage left) row (secret left) -
      message (leakage left) row (secret right)
  let errorDifference := error left row - error right row
  have hmessage : InPrincipalIdeal difference messageDifference :=
    hcompatible (leakage left) row (secret left) (secret right)
  have hmembership :
      InPrincipalIdeal difference (-(messageDifference + errorDifference)) ↔
        InPrincipalIdeal difference errorDifference :=
    principalMembership_collisionTarget_iff
      difference messageDifference errorDifference hmessage
  have hequation (mask : R) :
      (mask * secret left +
            message (leakage left) row (secret left) + error left row =
          mask * secret right +
            message (leakage right) row (secret right) + error right row) ↔
        mask * difference = -(messageDifference + errorDifference) := by
    rw [← hsame]
    dsimp only [difference, messageDifference, errorDifference]
    constructor <;> intro h <;> linear_combination h
  simp_rw [hequation]
  rw [rightMulFiberCount]
  unfold rowIdealCollisionWeight principalFiberWeight
  rw [if_congr hmembership rfl rfl]

/-- Exact complete-mask collision count for a same-leakage pair of source tapes. -/
theorem affineMaskCollisionCount
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Row]
    [DecidableEq R] [DecidableEq Row]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (hcompatible : IdealCompatible message)
    (left right : Seed) (hsame : leakage left = leakage right) :
    (∑ mask : Row → R,
      if affineBody secret error leakage message left mask =
          affineBody secret error leakage message right mask
      then (1 : ℝ) else 0) =
      pairIdealCollisionWeight secret error left right := by
  classical
  let predicate : Row → R → Prop := fun row value ↦
    value * secret left +
          message (leakage left) row (secret left) + error left row =
      value * secret right +
          message (leakage right) row (secret right) + error right row
  calc
    (∑ mask : Row → R,
        if affineBody secret error leakage message left mask =
            affineBody secret error leakage message right mask
        then (1 : ℝ) else 0) =
      ∑ mask : Row → R,
        if ∀ row, predicate row (mask row) then (1 : ℝ) else 0 := by
      apply Finset.sum_congr rfl
      intro mask _
      by_cases heq : affineBody secret error leakage message left mask =
          affineBody secret error leakage message right mask
      · have hall : ∀ row, predicate row (mask row) := by
          intro row
          have := congrFun heq row
          simpa only [predicate, affineBody] using this
        simp [heq, hall]
      · have hnall : ¬ ∀ row, predicate row (mask row) := by
          intro hall
          apply heq
          funext row
          simpa only [predicate, affineBody] using hall row
        simp [heq, hnall]
    _ = ∏ row : Row,
        ∑ value : R, if predicate row value then (1 : ℝ) else 0 :=
      sum_pi_indicator_eq_prod predicate
    _ = pairIdealCollisionWeight secret error left right := by
      unfold pairIdealCollisionWeight
      apply Finset.prod_congr rfl
      intro row _
      exact affineRowMaskCollisionCount secret error leakage message
        hcompatible left right row hsame

/-- Exact two-mask transcript collision count for a same-leakage pair. -/
theorem affineTranscriptCollisionCount
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Row]
    [DecidableEq R] [DecidableEq Row]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (hcompatible : IdealCompatible message)
    (left right : Seed) (hsame : leakage left = leakage right) :
    (∑ leftMask : Row → R, ∑ rightMask : Row → R,
      if affineTranscript secret error leakage message left leftMask =
          affineTranscript secret error leakage message right rightMask
      then (1 : ℝ) else 0) =
      pairIdealCollisionWeight secret error left right := by
  change (∑ leftMask : Row → R, ∑ rightMask : Row → R,
      if (leftMask, affineBody secret error leakage message left leftMask) =
          (rightMask, affineBody secret error leakage message right rightMask)
      then (1 : ℝ) else 0) = _
  rw [transcriptPairCollisionCount_eq_singleMask
    (fun mask ↦ affineBody secret error leakage message left mask)
    (fun mask ↦ affineBody secret error leakage message right mask)]
  exact affineMaskCollisionCount secret error leakage message
    hcompatible left right hsame

/-! ## The strong finite-ring theorem -/

/-- Retained leakage as a function of the complete source-and-mask tape. -/
def affineSide {R Seed Side Row : Type}
    (leakage : Seed → Side) : Seed × (Row → R) → Side :=
  fun input ↦ leakage input.1

/-- Affine transcript as a function of the complete source-and-mask tape. -/
def affineOutput {R Seed Side Row : Type} [CommRing R]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row) :
    Seed × (Row → R) → QuadraticKDM.TargetTranscript R Row :=
  fun input ↦ affineTranscript secret error leakage message input.1 input.2

/-- The explicit conditional-copy moment from the finite-ring theorem, scaled by `|R|^ell`.
The factor for a row is `|R| / |(S-S')R|` on the required ideal-membership event. -/
noncomputable def affineIdealCollisionMoment
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Fintype Side] [Fintype Row]
    [DecidableEq Side]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) : ℝ := by
  classical
  exact ∑ leakageValue : Side,
    if FormalProof4FHE.ConditionalCollision.sideFiberCard
        leakage leakageValue = 0 then 0
    else
      (∑ left : Seed, ∑ right : Seed,
        if leakage left = leakageValue ∧ leakage right = leakageValue then
          pairIdealCollisionWeight secret error left right
        else 0) /
      ((Fintype.card Seed : ℝ) *
        FormalProof4FHE.ConditionalCollision.sideFiberCard
          leakage leakageValue)

theorem affineConditionalCollisionPairCount
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (hcompatible : IdealCompatible message) (leakageValue : Side) :
    FormalProof4FHE.ConditionalCollision.conditionalFiberCollisionPairCount
        (affineSide (R := R) (Row := Row) leakage)
        (affineOutput secret error leakage message) leakageValue =
      ∑ left : Seed, ∑ right : Seed,
        if leakage left = leakageValue ∧ leakage right = leakageValue then
          pairIdealCollisionWeight secret error left right
        else 0 := by
  classical
  unfold affineSide affineOutput
  rw [FormalProof4FHE.ConditionalCollision.conditionalFiberCollisionPairCount_prod]
  apply Finset.sum_congr rfl
  intro left _
  apply Finset.sum_congr rfl
  intro right _
  by_cases hside :
      leakage left = leakageValue ∧ leakage right = leakageValue
  · rw [if_pos hside]
    simpa [hside.1, hside.2] using
      (affineTranscriptCollisionCount secret error leakage message
        hcompatible left right (hside.1.trans hside.2.symm))
  · simp only [hside, if_false]

/-- The normalized collision second moment of affine rows is exactly the explicit
principal-ideal moment. -/
theorem card_mul_affineConditionalSecondMoment_eq
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (hcompatible : IdealCompatible message) :
    (Fintype.card (QuadraticKDM.TargetTranscript R Row) : ℝ) /
          Fintype.card (Seed × (Row → R)) *
        FormalProof4FHE.ConditionalCollision.conditionalFiberSecondMoment
          (affineSide (R := R) (Row := Row) leakage)
          (affineOutput secret error leakage message) =
      affineIdealCollisionMoment secret error leakage := by
  classical
  let Mask := Row → R
  let maskCard : ℝ := Fintype.card Mask
  let seedCard : ℝ := Fintype.card Seed
  have hMaskNat : Fintype.card Mask ≠ 0 := Fintype.card_ne_zero
  have hMask : maskCard ≠ 0 := by
    dsimp only [maskCard]
    exact_mod_cast hMaskNat
  have hSeed : seedCard ≠ 0 := by
    dsimp only [seedCard]
    exact_mod_cast (Fintype.card_ne_zero : Fintype.card Seed ≠ 0)
  rw [FormalProof4FHE.ConditionalCollision.conditionalFiberSecondMoment_eq_collisionPairCount]
  unfold affineIdealCollisionMoment
  have hSideFiber (leakageValue : Side) :
      FormalProof4FHE.ConditionalCollision.sideFiberCard
          (affineSide (R := R) (Row := Row) leakage) leakageValue =
        Fintype.card Mask *
          FormalProof4FHE.ConditionalCollision.sideFiberCard
            leakage leakageValue := by
    exact FormalProof4FHE.ConditionalCollision.sideFiberCard_prod_fst
      leakage leakageValue
  simp_rw [affineConditionalCollisionPairCount secret error leakage message
      hcompatible, hSideFiber]
  simp only [Fintype.card_prod, Nat.cast_mul]
  change
    (maskCard * maskCard) / (seedCard * maskCard) *
        (∑ leakageValue : Side,
          if Fintype.card Mask *
              FormalProof4FHE.ConditionalCollision.sideFiberCard
                leakage leakageValue = 0 then 0
          else
            (∑ left : Seed, ∑ right : Seed,
              if leakage left = leakageValue ∧
                  leakage right = leakageValue then
                pairIdealCollisionWeight secret error left right
              else 0) /
              (Fintype.card Mask *
                FormalProof4FHE.ConditionalCollision.sideFiberCard
                  leakage leakageValue)) =
      ∑ leakageValue : Side,
        if FormalProof4FHE.ConditionalCollision.sideFiberCard
            leakage leakageValue = 0 then 0
        else
          (∑ left : Seed, ∑ right : Seed,
            if leakage left = leakageValue ∧
                leakage right = leakageValue then
              pairIdealCollisionWeight secret error left right
            else 0) /
            (seedCard *
              FormalProof4FHE.ConditionalCollision.sideFiberCard
                leakage leakageValue)
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro leakageValue _
  let fiberCard := FormalProof4FHE.ConditionalCollision.sideFiberCard
    leakage leakageValue
  by_cases hfiber : fiberCard = 0
  · simp [fiberCard, hfiber]
  · have hfiberReal : (fiberCard : ℝ) ≠ 0 := by exact_mod_cast hfiber
    have hproduct : Fintype.card Mask * fiberCard ≠ 0 :=
      mul_ne_zero hMaskNat hfiber
    simp only [fiberCard, hfiber, hproduct, if_false]
    field_simp [hMask, hSeed, hfiberReal]
    ring

/-- Exact Pearson divergence identity behind the strong affine collision theorem. -/
theorem affineConditionalChiSquare_eq_moment_sub_one
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (hcompatible : IdealCompatible message) :
    FormalProof4FHE.ConditionalCollision.conditionalFiberChiSquare
        (affineSide (R := R) (Row := Row) leakage)
        (affineOutput secret error leakage message) =
      affineIdealCollisionMoment secret error leakage - 1 := by
  rw [FormalProof4FHE.ConditionalCollision.conditionalFiberChiSquare_eq_secondMoment]
  rw [card_mul_affineConditionalSecondMoment_eq
    secret error leakage message hcompatible]

/-- **Strong affine collision theorem.**  Every ideal-compatible affine family is close to the
same leakage-preserving uniform experiment, with a bound that contains no message term. -/
theorem tvDist_affineJoint_ideal_le
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (message : MessageFamily R Side Row)
    (hcompatible : IdealCompatible message) :
    tvDist (affineJointSampler secret error leakage message)
        (affineIdealSampler (R := R) (Row := Row) leakage) ≤
      Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) / 2 := by
  unfold affineJointSampler affineIdealSampler
  calc
    tvDist
        (FormalProof4FHE.ConditionalCollision.uniformJointImage
          (affineSide (R := R) (Row := Row) leakage)
          (affineOutput secret error leakage message))
        (FormalProof4FHE.ConditionalCollision.uniformSideIndependentOutput
          (Output := QuadraticKDM.TargetTranscript R Row)
          (affineSide (R := R) (Row := Row) leakage)) ≤
        Real.sqrt
          (FormalProof4FHE.ConditionalCollision.conditionalFiberChiSquare
            (affineSide (R := R) (Row := Row) leakage)
            (affineOutput secret error leakage message)) / 2 :=
      FormalProof4FHE.ConditionalCollision.tvDist_uniformJointImage_sideIndependent_le_chiSquare
        _ _
    _ = Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) / 2 := by
      rw [affineConditionalChiSquare_eq_moment_sub_one
        secret error leakage message hcompatible]

/-! ## Quadratic and zero-message consequences -/

theorem tvDist_quadratic_ideal_le
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (weight : Row → R) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineIdealSampler (R := R) (Row := Row) leakage) ≤
      Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) / 2 :=
  tvDist_affineJoint_ideal_le secret error leakage _
    (idealCompatible_quadratic weight)

theorem tvDist_zero_ideal_le
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) :
    tvDist
        (affineJointSampler secret error leakage
          (fun (_leakage : Side) (_row : Row) (_value : R) ↦ 0))
        (affineIdealSampler (R := R) (Row := Row) leakage) ≤
      Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) / 2 :=
  tvDist_affineJoint_ideal_le secret error leakage _ idealCompatible_zero

/-- Quadratic KDM and zero-message rows are at most twice their common distance from uniform. -/
theorem tvDist_quadratic_zero_le
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (weight : Row → R) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineJointSampler secret error leakage
          (fun (_leakage : Side) (_row : Row) (_value : R) ↦ 0)) ≤
      Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) := by
  let ideal := affineIdealSampler (R := R) (Row := Row) leakage
  calc
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineJointSampler secret error leakage
          (fun (_leakage : Side) (_row : Row) (_value : R) ↦ 0)) ≤
        tvDist
          (affineJointSampler secret error leakage
            (fun _leakage row value ↦ weight row * value ^ 2)) ideal +
        tvDist ideal
          (affineJointSampler secret error leakage
            (fun (_leakage : Side) (_row : Row) (_value : R) ↦ 0)) :=
      tvDist_triangle _ ideal _
    _ ≤ Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) / 2 +
        Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) / 2 := by
      apply add_le_add
      · exact tvDist_quadratic_ideal_le secret error leakage weight
      · simpa only [ideal, tvDist_comm] using
          (tvDist_zero_ideal_le secret error leakage)
    _ = Real.sqrt (affineIdealCollisionMoment secret error leakage - 1) := by ring

/-! ## Ramified power-of-two chain-ring specialization -/

/-- The exact finite algebraic data used by the `pi`-adic specialization.  In addition to the
principal-ideal and cardinality formulas used by the proof, `idealChain` records the statement
that every ideal is one of the displayed powers.  Thus an instantiation cannot silently assume
the chain-ring step from the paper.

For the literal cyclotomic quotient the intended values are `length = kappa * n` and
`uniformizer = 1 - zeta_(2*n)`. -/
structure FiniteAdicChain (R : Type)
    [CommRing R] [Fintype R] [DecidableEq R] where
  uniformizer : R
  length : ℕ
  valuation : R → ℕ
  valuation_le : ∀ value, valuation value ≤ length
  principal_eq : ∀ value,
    (rightMulAddHom value).range =
      (rightMulAddHom (uniformizer ^ valuation value)).range
  card_ring : Nat.card R = 2 ^ length
  card_power : ∀ level, level ≤ length →
    Nat.card (rightMulAddHom (uniformizer ^ level)).range =
      2 ^ (length - level)
  idealChain : ∀ ideal : Ideal R, ∃ level ≤ length,
    ideal.toAddSubgroup =
      (rightMulAddHom (uniformizer ^ level)).range

/-- The multiplication-fiber weight in a certified binary chain ring is exactly `2^val` times
the corresponding `pi^val` membership indicator. -/
theorem principalFiberWeight_eq_adic
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (chain : FiniteAdicChain R) (difference target : R) :
    principalFiberWeight difference target =
      if InPrincipalIdeal
          (chain.uniformizer ^ chain.valuation difference) target then
        (2 : ℝ) ^ chain.valuation difference
  else 0 := by
  classical
  have hmembership :
      InPrincipalIdeal difference target ↔
        InPrincipalIdeal
          (chain.uniformizer ^ chain.valuation difference) target := by
    unfold InPrincipalIdeal
    rw [chain.principal_eq difference]
  have hcardPrincipal :
      Nat.card (rightMulAddHom difference).range =
        Nat.card
          (rightMulAddHom
            (chain.uniformizer ^ chain.valuation difference)).range := by
    let equivalence : (rightMulAddHom difference).range ≃
        (rightMulAddHom
          (chain.uniformizer ^ chain.valuation difference)).range := {
      toFun := fun value ↦ ⟨value.1, by
        rw [← chain.principal_eq difference]
        exact value.2⟩
      invFun := fun value ↦ ⟨value.1, by
        rw [chain.principal_eq difference]
        exact value.2⟩
      left_inv := fun value ↦ Subtype.ext rfl
      right_inv := fun value ↦ Subtype.ext rfl
    }
    exact Nat.card_congr equivalence
  have hlevel : chain.valuation difference ≤ chain.length :=
    chain.valuation_le difference
  by_cases htarget : InPrincipalIdeal difference target
  · have hadic := hmembership.mp htarget
    unfold principalFiberWeight
    rw [if_pos htarget, if_pos hadic]
    simp only [← Nat.card_eq_fintype_card]
    rw [hcardPrincipal, chain.card_ring,
      chain.card_power (chain.valuation difference)
        hlevel]
    simp only [Nat.cast_pow, Nat.cast_ofNat]
    apply (div_eq_iff (by positivity :
      (2 : ℝ) ^ (chain.length - chain.valuation difference) ≠ 0)).2
    rw [← pow_add]
    congr 1
    omega
  · have hadic := not_congr hmembership |>.mp htarget
    unfold principalFiberWeight
    rw [if_neg htarget, if_neg hadic]

/-- One conditional source-pair contribution in the power-of-two theorem. -/
noncomputable def adicPairCollisionWeight
    {R Seed Row : Type}
    [CommRing R] [Fintype R] [DecidableEq R] [Fintype Row]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (left right : Seed) : ℝ := by
  classical
  exact ∏ row : Row,
    if InPrincipalIdeal
        (chain.uniformizer ^ chain.valuation (secret left - secret right))
        (error left row - error right row) then
      (2 : ℝ) ^ chain.valuation (secret left - secret right)
    else 0

/-- Exact `Theta` of the paper, including the leakage-conditioned independent-copy
normalization. -/
noncomputable def powerOfTwoTheta
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [DecidableEq R] [Fintype Seed]
    [Fintype Side] [DecidableEq Side] [Fintype Row]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) : ℝ := by
  classical
  exact ∑ leakageValue : Side,
    if FormalProof4FHE.ConditionalCollision.sideFiberCard
        leakage leakageValue = 0 then 0
    else
      (∑ left : Seed, ∑ right : Seed,
        if leakage left = leakageValue ∧ leakage right = leakageValue then
          adicPairCollisionWeight chain secret error left right
        else 0) /
      ((Fintype.card Seed : ℝ) *
        FormalProof4FHE.ConditionalCollision.sideFiberCard
          leakage leakageValue)

theorem pairIdealCollisionWeight_eq_adic
    {R Seed Row : Type}
    [CommRing R] [Fintype R] [DecidableEq R] [Fintype Row]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (left right : Seed) :
    pairIdealCollisionWeight secret error left right =
      adicPairCollisionWeight chain secret error left right := by
  classical
  unfold pairIdealCollisionWeight rowIdealCollisionWeight
    adicPairCollisionWeight
  apply Finset.prod_congr rfl
  intro row _
  exact principalFiberWeight_eq_adic chain _ _

/-- The generic finite-ring moment specializes exactly to the `pi`-adic `Theta`. -/
theorem affineIdealCollisionMoment_eq_powerOfTwoTheta
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [DecidableEq R] [Fintype Seed]
    [Fintype Side] [DecidableEq Side] [Fintype Row]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) :
    affineIdealCollisionMoment secret error leakage =
      powerOfTwoTheta chain secret error leakage := by
  classical
  unfold affineIdealCollisionMoment powerOfTwoTheta
  apply Finset.sum_congr rfl
  intro leakageValue _
  by_cases hfiber : FormalProof4FHE.ConditionalCollision.sideFiberCard
      leakage leakageValue = 0
  · simp [hfiber]
  · simp only [hfiber, if_false]
    congr 1
    apply Finset.sum_congr rfl
    intro left _
    apply Finset.sum_congr rfl
    intro right _
    by_cases hside :
        leakage left = leakageValue ∧ leakage right = leakageValue
    · simp [hside, pairIdealCollisionWeight_eq_adic chain]
    · simp [hside]

/-- Product form of `Theta` is the displayed `2^(ell*V)` membership expression. -/
theorem adicPairCollisionWeight_eq_pow_mul_indicator
    {R Seed Row : Type}
    [CommRing R] [Fintype R] [DecidableEq R]
    [Fintype Row] [DecidableEq Row]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (left right : Seed) :
    adicPairCollisionWeight chain secret error left right =
      (2 : ℝ) ^
          (Fintype.card Row * chain.valuation (secret left - secret right)) *
        if ∀ row,
          InPrincipalIdeal
            (chain.uniformizer ^
              chain.valuation (secret left - secret right))
            (error left row - error right row) then 1 else 0 := by
  classical
  let level := chain.valuation (secret left - secret right)
  let good := fun row : Row ↦ InPrincipalIdeal
    (chain.uniformizer ^ level) (error left row - error right row)
  by_cases hall : ∀ row, good row
  · unfold adicPairCollisionWeight
    simp only [level, good] at hall ⊢
    simp [hall, Finset.prod_const]
    rw [Nat.mul_comm]
    rw [← pow_mul]
  · obtain ⟨row, hrow⟩ := Classical.not_forall.mp hall
    have hzero :
        (∏ row : Row, if good row then (2 : ℝ) ^ level else 0) = 0 := by
      apply Finset.prod_eq_zero (Finset.mem_univ row)
      simp [hrow]
    unfold adicPairCollisionWeight
    simp only [level, good] at hall hzero ⊢
    rw [hzero, if_neg hall, mul_zero]

/-- Direct power-of-two quadratic KDM-to-uniform bound. -/
theorem tvDist_quadratic_ideal_le_powerOfTwoTheta
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (weight : Row → R) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineIdealSampler (R := R) (Row := Row) leakage) ≤
      Real.sqrt (powerOfTwoTheta chain secret error leakage - 1) / 2 := by
  simpa only [affineIdealCollisionMoment_eq_powerOfTwoTheta
    chain secret error leakage] using
    (tvDist_quadratic_ideal_le secret error leakage weight)

/-- The analogous zero-message-to-uniform power-of-two bound. -/
theorem tvDist_zero_ideal_le_powerOfTwoTheta
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) :
    tvDist
        (affineJointSampler secret error leakage
          (fun (_leakage : Side) (_row : Row) (_value : R) ↦ 0))
        (affineIdealSampler (R := R) (Row := Row) leakage) ≤
      Real.sqrt (powerOfTwoTheta chain secret error leakage - 1) / 2 := by
  simpa only [affineIdealCollisionMoment_eq_powerOfTwoTheta
    chain secret error leakage] using
    (tvDist_zero_ideal_le secret error leakage)

/-- The analogous quadratic-KDM-to-zero power-of-two bound. -/
theorem tvDist_quadratic_zero_le_powerOfTwoTheta
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (weight : Row → R) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineJointSampler secret error leakage
          (fun (_leakage : Side) (_row : Row) (_value : R) ↦ 0)) ≤
      Real.sqrt (powerOfTwoTheta chain secret error leakage - 1) := by
  simpa only [affineIdealCollisionMoment_eq_powerOfTwoTheta
    chain secret error leakage] using
    (tvDist_quadratic_zero_le secret error leakage weight)

/-- The paper's convenient numerical threshold: `Theta ≤ 1 + 4*epsilon^2` turns the
square-root expression into `epsilon`. -/
theorem sqrt_theta_sub_one_div_two_le
    {theta epsilon : ℝ} (hepsilon : 0 ≤ epsilon)
    (htheta : theta ≤ 1 + 4 * epsilon ^ 2) :
    Real.sqrt (theta - 1) / 2 ≤ epsilon := by
  have hinside : theta - 1 ≤ 4 * epsilon ^ 2 := by linarith
  calc
    Real.sqrt (theta - 1) / 2 ≤ Real.sqrt (4 * epsilon ^ 2) / 2 := by
      gcongr
    _ = epsilon := by
      rw [show 4 * epsilon ^ 2 = (2 * epsilon) ^ 2 by ring,
        Real.sqrt_sq_eq_abs, abs_of_nonneg (mul_nonneg (by norm_num) hepsilon)]
      ring

/-- `Theta ≤ 1 + 4*epsilon^2` makes quadratic KDM rows `epsilon`-close to uniform. -/
theorem tvDist_quadratic_ideal_le_epsilon
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (weight : Row → R) (epsilon : ℝ)
    (hepsilon : 0 ≤ epsilon)
    (htheta : powerOfTwoTheta chain secret error leakage ≤
      1 + 4 * epsilon ^ 2) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineIdealSampler (R := R) (Row := Row) leakage) ≤ epsilon :=
  (tvDist_quadratic_ideal_le_powerOfTwoTheta
    chain secret error leakage weight).trans
      (sqrt_theta_sub_one_div_two_le hepsilon htheta)

/-! ## Literal executable ring facts already discharged in the library -/

/-- The executable degree-`2^r` ring at coefficient modulus `2^kappa` has the exact cardinality
`2^(kappa * 2^r)`.  This discharges the carrier-size field of the intended chain certificate. -/
theorem card_powerOfTwoRq (kappa degreeExponent : ℕ) [NeZero (2 ^ kappa)] :
    Fintype.card (Rq (2 ^ kappa) (2 ^ degreeExponent)) =
      2 ^ (kappa * 2 ^ degreeExponent) := by
  rw [RingRegev.card_rq, pow_mul]

/-- An optional representation-level witness for the executable coefficient carrier.  The
companion `PowerOfTwoCyclotomicChainRing` module proves the complete chain theorem directly for
the semantic quotient.  This record is retained for clients that want the same data attached to
the executable carrier despite its two legacy multiplication-instance presentations. -/
structure PowerOfTwoRqChainCertificate
    (kappa degreeExponent : ℕ) [NeZero (2 ^ kappa)] where
  chain : FiniteAdicChain (Rq (2 ^ kappa) (2 ^ degreeExponent))
  length_eq : chain.length = kappa * 2 ^ degreeExponent

/-! ## Correlated HNF source and exact compiler -/

/-- Eliminate the public HNF anchor from one body. -/
def eliminateAnchor {R : Type} [Ring R]
    (anchor coefficient body : R) : R :=
  body - coefficient * anchor

/-- Anchor elimination is a translation, hence a permutation when the retained anchor and
coefficient are fixed. -/
theorem eliminateAnchor_bijective
    {R : Type} [Ring R] (anchor coefficient : R) :
    Function.Bijective (fun body ↦ eliminateAnchor anchor coefficient body) := by
  let inverse := fun output : R ↦ output + coefficient * anchor
  exact Function.bijective_iff_has_inverse.mpr ⟨inverse,
    (fun body ↦ by simp [inverse, eliminateAnchor]),
    (fun output ↦ by simp [inverse, eliminateAnchor])⟩

/-- In the real HNF source, anchor elimination produces the masked quadratic affine row from
the paper. -/
theorem eliminateAnchor_real
    {R : Type} [CommRing R]
    (auxiliarySecret secret proofMask coefficient weight error : R) :
    eliminateAnchor (auxiliarySecret - secret) coefficient
        (coefficient * auxiliarySecret + weight * proofMask ^ 2 + error) =
      coefficient * secret +
        weight * (secret - (secret - proofMask)) ^ 2 + error := by
  unfold eliminateAnchor
  ring

/-- Additive translation makes the real anchor uniform for every fixed secret. -/
theorem anchorTranslation_bijective
    {R : Type} [AddGroup R] (secret : R) :
    Function.Bijective (fun auxiliarySecret ↦ auxiliarySecret - secret) := by
  let inverse := fun anchor : R ↦ anchor + secret
  exact Function.bijective_iff_has_inverse.mpr ⟨inverse,
    (fun auxiliarySecret ↦ by simp [inverse]),
    (fun anchor ↦ by simp [inverse])⟩

/-- One-row public two-component compiler. -/
def hnfCompileRow {R : Type} [CommRing R]
    (weight leakage anchor : R) (source : R × R) : R × R :=
  (source.1 - 2 * weight * leakage,
    source.2 - source.1 * anchor - weight * leakage ^ 2)

/-- Explicit inverse of the one-row compiler. -/
def hnfCompileRowInv {R : Type} [CommRing R]
    (weight leakage anchor : R) (target : R × R) : R × R :=
  let coefficient := target.1 + 2 * weight * leakage
  (coefficient,
    target.2 + coefficient * anchor + weight * leakage ^ 2)

theorem hnfCompileRowInv_hnfCompileRow
    {R : Type} [CommRing R]
    (weight leakage anchor : R) (source : R × R) :
    hnfCompileRowInv weight leakage anchor
        (hnfCompileRow weight leakage anchor source) = source := by
  apply Prod.ext
  · simp [hnfCompileRowInv, hnfCompileRow]
  · simp [hnfCompileRowInv, hnfCompileRow]
    ring

theorem hnfCompileRow_hnfCompileRowInv
    {R : Type} [CommRing R]
    (weight leakage anchor : R) (target : R × R) :
    hnfCompileRow weight leakage anchor
        (hnfCompileRowInv weight leakage anchor target) = target := by
  apply Prod.ext
  · simp [hnfCompileRowInv, hnfCompileRow]
  · simp [hnfCompileRowInv, hnfCompileRow]
    ring

theorem hnfCompileRow_bijective
    {R : Type} [CommRing R]
    (weight leakage anchor : R) :
    Function.Bijective (hnfCompileRow weight leakage anchor) :=
  Function.bijective_iff_has_inverse.mpr
    ⟨hnfCompileRowInv weight leakage anchor,
      hnfCompileRowInv_hnfCompileRow weight leakage anchor,
      hnfCompileRow_hnfCompileRowInv weight leakage anchor⟩

/-- Row-vector form of the public compiler. -/
def hnfCompile {R Row : Type} [CommRing R]
    (weight : Row → R) (leakage anchor : R)
    (source : QuadraticKDM.TargetTranscript R Row) :
    QuadraticKDM.TargetTranscript R Row :=
  (fun row ↦ (hnfCompileRow (weight row) leakage anchor
      (source.1 row, source.2 row)).1,
    fun row ↦ (hnfCompileRow (weight row) leakage anchor
      (source.1 row, source.2 row)).2)

/-- Explicit vector inverse. -/
def hnfCompileInv {R Row : Type} [CommRing R]
    (weight : Row → R) (leakage anchor : R)
    (target : QuadraticKDM.TargetTranscript R Row) :
    QuadraticKDM.TargetTranscript R Row :=
  (fun row ↦ (hnfCompileRowInv (weight row) leakage anchor
      (target.1 row, target.2 row)).1,
    fun row ↦ (hnfCompileRowInv (weight row) leakage anchor
      (target.1 row, target.2 row)).2)

theorem hnfCompileInv_hnfCompile
    {R Row : Type} [CommRing R]
    (weight : Row → R) (leakage anchor : R)
    (source : QuadraticKDM.TargetTranscript R Row) :
    hnfCompileInv weight leakage anchor
        (hnfCompile weight leakage anchor source) = source := by
  apply Prod.ext <;> funext row
  · exact congrArg Prod.fst
      (hnfCompileRowInv_hnfCompileRow
        (weight row) leakage anchor (source.1 row, source.2 row))
  · exact congrArg Prod.snd
      (hnfCompileRowInv_hnfCompileRow
        (weight row) leakage anchor (source.1 row, source.2 row))

theorem hnfCompile_hnfCompileInv
    {R Row : Type} [CommRing R]
    (weight : Row → R) (leakage anchor : R)
    (target : QuadraticKDM.TargetTranscript R Row) :
    hnfCompile weight leakage anchor
        (hnfCompileInv weight leakage anchor target) = target := by
  apply Prod.ext <;> funext row
  · exact congrArg Prod.fst
      (hnfCompileRow_hnfCompileRowInv
        (weight row) leakage anchor (target.1 row, target.2 row))
  · exact congrArg Prod.snd
      (hnfCompileRow_hnfCompileRowInv
        (weight row) leakage anchor (target.1 row, target.2 row))

/-- Conditioned on the retained HNF context, the public compiler is a permutation of all
coefficient/body vectors. -/
theorem hnfCompile_bijective
    {R Row : Type} [CommRing R]
    (weight : Row → R) (leakage anchor : R) :
    Function.Bijective (hnfCompile weight leakage anchor) :=
  Function.bijective_iff_has_inverse.mpr
    ⟨hnfCompileInv weight leakage anchor,
      hnfCompileInv_hnfCompile weight leakage anchor,
      hnfCompile_hnfCompileInv weight leakage anchor⟩

/-- Consequently the random HNF source maps exactly to uniform target pairs. -/
theorem hnfCompile_uniform_evalDist
    {R Row : Type} [CommRing R]
    [Fintype R] [DecidableEq R] [Fintype Row] [DecidableEq Row]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (weight : Row → R) (leakage anchor : R) :
    evalDist
        (hnfCompile weight leakage anchor <$>
          ($ᵗ (QuadraticKDM.TargetTranscript R Row))) =
      evalDist ($ᵗ (QuadraticKDM.TargetTranscript R Row)) := by
  exact evalDist_map_bijective_uniform_cross
    (QuadraticKDM.TargetTranscript R Row)
    (hnfCompile weight leakage anchor)
    (hnfCompile_bijective weight leakage anchor)

/-- Exact real-branch compiler equation `B = A*S + g*S^2 + E`. -/
theorem hnfCompileRow_real
    {R : Type} [CommRing R]
    (auxiliarySecret secret proofMask coefficient weight error : R) :
    hnfCompileRow weight (secret - proofMask) (auxiliarySecret - secret)
        (coefficient,
          coefficient * auxiliarySecret + weight * proofMask ^ 2 + error) =
      (coefficient - 2 * weight * (secret - proofMask),
        (coefficient - 2 * weight * (secret - proofMask)) * secret +
          weight * secret ^ 2 + error) := by
  apply Prod.ext
  · simp [hnfCompileRow]
  · simp [hnfCompileRow]
    ring

/-- Statistical HNF theorem after anchor elimination.  The proof-only mask may affect the
posterior source-pair law through leakage, but the public weights do not occur in `Theta`. -/
theorem tvDist_maskedQuadratic_ideal_le_powerOfTwoTheta
    {R Seed Side Row : Type}
    [CommRing R] [Fintype R] [Fintype Seed] [Nonempty Seed]
    [Fintype Side] [Fintype Row]
    [DecidableEq R] [DecidableEq Side] [DecidableEq Row]
    [SampleableType (Seed × (Row → R))]
    [SampleableType (QuadraticKDM.TargetTranscript R Row)]
    (chain : FiniteAdicChain R)
    (secret : Seed → R) (error : Seed → Row → R)
    (leakage : Seed → Side) (proofMask : Side → R)
    (weight : Row → R) :
    tvDist
        (affineJointSampler secret error leakage
          (fun leakageValue row value ↦
            weight row * (value - proofMask leakageValue) ^ 2))
        (affineIdealSampler (R := R) (Row := Row) leakage) ≤
      Real.sqrt (powerOfTwoTheta chain secret error leakage - 1) / 2 := by
  rw [← affineIdealCollisionMoment_eq_powerOfTwoTheta
    chain secret error leakage]
  exact tvDist_affineJoint_ideal_le secret error leakage _
    (idealCompatible_maskedQuadratic weight proofMask)

/-! ## Relinearization correctness -/

/-- The implemented relinearization phase has exactly the original quadratic phase plus the
digit-weighted evaluation-key error; all proof-only HNF variables have disappeared. -/
theorem relinearization_correct
    {R Row : Type} [CommRing R] [Fintype Row]
    (secret c0 c1 c2 : R) (digit weight mask error : Row → R)
    (hDecomposition : c2 = ∑ row, digit row * weight row) :
    (c0 + ∑ row, digit row *
        (mask row * secret + weight row * secret ^ 2 + error row)) +
        (c1 - ∑ row, digit row * mask row) * secret =
      c0 + c1 * secret + c2 * secret ^ 2 +
        ∑ row, digit row * error row := by
  simpa only [QuadraticKDM.evaluationKeyBody] using
    (QuadraticKDM.relinearization_phase
      secret c0 c1 c2 digit weight mask error hDecomposition)

end

end FormalProof4FHE.RLWE.PowerOfTwoQuadraticKDMStatistical
