/-
Copyright (c) 2026 Kotaro Matsuoka. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Kotaro Matsuoka
-/

import FormalProof4FHE.RLWE.PowerOfTwoQuadraticKDMStatistical
import FormalProof4FHE.TFHE.NativePowerOfTwoLocalRing

/-!
# The chain ring at a literal power-of-two cyclotomic modulus

This module discharges the algebraic certificate used by the statistical quadratic-KDM theorem
for the literal quotient
`ZMod (2^kappa)[X] / (X^(2^r) + 1)`.  The proof is elementary and finite:

* parity evaluation has principal kernel generated by `1 - X`;
* `(1 - X)^(kappa * 2^r) = 0` in the quotient;
* the quotient has `2^(kappa * 2^r)` elements; and
* a finite local ring with these facts has exactly the ideal chain generated by powers of
  `1 - X`, with the claimed cardinality at every level.

No algebraic-number-theory ramification theorem is assumed.
-/

open BigOperators

namespace FormalProof4FHE.RLWE.PowerOfTwoQuadraticKDMStatistical

noncomputable section

def adicPower {R : Type} [CommRing R] (uniformizer : R) (level : ℕ) : AddSubgroup R :=
  (rightMulAddHom (uniformizer ^ level)).range

def truncatedValuation {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (uniformizer : R) (length : ℕ) (value : R) : ℕ := by
  classical
  exact Nat.findGreatest (fun level ↦ value ∈ adicPower uniformizer level) length

theorem truncatedValuation_le {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (uniformizer : R) (length : ℕ) (value : R) :
    truncatedValuation uniformizer length value ≤ length := by
  classical
  unfold truncatedValuation
  exact Nat.findGreatest_le _

theorem mem_adicPower_truncatedValuation
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (uniformizer : R) (length : ℕ) (value : R) :
    value ∈ adicPower uniformizer (truncatedValuation uniformizer length value) := by
  classical
  unfold truncatedValuation
  exact Nat.findGreatest_spec
    (P := fun level ↦ value ∈ adicPower uniformizer level)
    (m := 0) (Nat.zero_le length)
    ⟨value, by simp [rightMulAddHom]⟩

theorem adicPower_antitone {R : Type} [CommRing R]
    (uniformizer : R) {left right : ℕ} (hle : left ≤ right) :
    adicPower uniformizer right ≤ adicPower uniformizer left := by
  intro value hvalue
  obtain ⟨multiplier, rfl⟩ := hvalue
  obtain ⟨offset, rfl⟩ := Nat.exists_eq_add_of_le hle
  refine ⟨multiplier * uniformizer ^ offset, ?_⟩
  simp only [rightMulAddHom_apply]
  rw [pow_add]
  ring

theorem zmodTwo_eq_zero_or_one (value : ZMod 2) : value = 0 ∨ value = 1 := by
  have hlt := value.val_lt
  have hval : value.val = 0 ∨ value.val = 1 := by omega
  rcases hval with hval | hval
  · left
    apply ZMod.val_injective
    simpa using hval
  · right
    apply ZMod.val_injective
    simpa [ZMod.val_one] using hval

theorem adicPower_mem_or_sub_mem_succ
    {R : Type} [CommRing R]
    (residue : R →+* ZMod 2) (uniformizer : R)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (level : ℕ) {value : R} (hvalue : value ∈ adicPower uniformizer level) :
    value ∈ adicPower uniformizer (level + 1) ∨
      value - uniformizer ^ level ∈ adicPower uniformizer (level + 1) := by
  obtain ⟨multiplier, hmultiplier⟩ := hvalue
  rcases zmodTwo_eq_zero_or_one (residue multiplier) with hzero | hone
  · left
    have hmemKer : multiplier ∈ RingHom.ker residue := RingHom.mem_ker.mpr hzero
    have hmemKerAdd : multiplier ∈ (RingHom.ker residue).toAddSubgroup := hmemKer
    rw [hker] at hmemKerAdd
    obtain ⟨next, hnext⟩ := hmemKerAdd
    refine ⟨next, ?_⟩
    simp only [rightMulAddHom_apply] at hmultiplier hnext ⊢
    rw [← hmultiplier, ← hnext]
    simp only [pow_succ]
    ring
  · right
    have hmemKer : multiplier - 1 ∈ RingHom.ker residue := by
      apply RingHom.mem_ker.mpr
      rw [map_sub, map_one, hone, sub_self]
    have hmemKerAdd : multiplier - 1 ∈ (RingHom.ker residue).toAddSubgroup := hmemKer
    rw [hker] at hmemKerAdd
    obtain ⟨next, hnext⟩ := hmemKerAdd
    refine ⟨next, ?_⟩
    simp only [rightMulAddHom_apply] at hmultiplier hnext ⊢
    have hnext' : next * uniformizer = multiplier - 1 := by
      simpa only [pow_one] using hnext
    rw [← hmultiplier, pow_succ]
    calc
      next * (uniformizer ^ level * uniformizer) =
          (next * uniformizer) * uniformizer ^ level := by ring
      _ = (multiplier - 1) * uniformizer ^ level := by rw [hnext']
      _ = multiplier * uniformizer ^ level - uniformizer ^ level := by ring

def adicPowerBitCover {R : Type} [CommRing R]
    (uniformizer : R) (level : ℕ) :
    Bool × adicPower uniformizer (level + 1) → adicPower uniformizer level :=
  fun input ↦
    if input.1 then
      ⟨uniformizer ^ level + input.2.1, by
        exact (adicPower uniformizer level).add_mem
          ⟨1, by simp [rightMulAddHom]⟩
          (adicPower_antitone uniformizer (Nat.le_succ level) input.2.2)⟩
    else
      ⟨input.2.1,
        adicPower_antitone uniformizer (Nat.le_succ level) input.2.2⟩

theorem adicPowerBitCover_surjective
    {R : Type} [CommRing R]
    (residue : R →+* ZMod 2) (uniformizer : R)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (level : ℕ) :
    Function.Surjective (adicPowerBitCover uniformizer level) := by
  intro value
  rcases adicPower_mem_or_sub_mem_succ residue uniformizer hker level value.2 with
    hnext | hsub
  · refine ⟨(false, ⟨value, hnext⟩), ?_⟩
    apply Subtype.ext
    simp [adicPowerBitCover]
  · refine ⟨(true, ⟨value.1 - uniformizer ^ level, hsub⟩), ?_⟩
    apply Subtype.ext
    simp [adicPowerBitCover]

theorem card_adicPower_le_two_mul_succ
    {R : Type} [CommRing R] [Fintype R]
    (residue : R →+* ZMod 2) (uniformizer : R)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (level : ℕ) :
    Nat.card (adicPower uniformizer level) ≤
      2 * Nat.card (adicPower uniformizer (level + 1)) := by
  calc
    Nat.card (adicPower uniformizer level) ≤
        Nat.card (Bool × adicPower uniformizer (level + 1)) :=
      Nat.card_le_card_of_surjective _
        (adicPowerBitCover_surjective residue uniformizer hker level)
    _ = 2 * Nat.card (adicPower uniformizer (level + 1)) := by
      simp [Nat.card_eq_fintype_card]

theorem adicPower_eq_bot_of_pow_eq_zero
    {R : Type} [CommRing R]
    (uniformizer : R) (level : ℕ) (hzero : uniformizer ^ level = 0) :
    adicPower uniformizer level = ⊥ := by
  ext value
  constructor
  · rintro ⟨multiplier, hmultiplier⟩
    simp only [rightMulAddHom_apply, hzero, mul_zero] at hmultiplier
    subst value
    exact AddSubgroup.zero_mem ⊥
  · intro hvalue
    have : value = 0 := by simpa using hvalue
    subst value
    exact ⟨0, by simp⟩

theorem card_adicPower_le_pow_sub
    {R : Type} [CommRing R] [Fintype R]
    (residue : R →+* ZMod 2) (uniformizer : R) (length : ℕ)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (hzero : uniformizer ^ length = 0)
    (level : ℕ) (hlevel : level ≤ length) :
    Nat.card (adicPower uniformizer level) ≤ 2 ^ (length - level) := by
  induction hlevel using Nat.decreasingInduction with
  | self =>
      rw [adicPower_eq_bot_of_pow_eq_zero uniformizer length hzero]
      simp
  | of_succ level hlt ih =>
      calc
        Nat.card (adicPower uniformizer level) ≤
            2 * Nat.card (adicPower uniformizer (level + 1)) :=
          card_adicPower_le_two_mul_succ residue uniformizer hker level
        _ ≤ 2 * 2 ^ (length - (level + 1)) :=
          Nat.mul_le_mul_left 2 ih
        _ = 2 ^ (length - level) := by
          rw [show length - level = (length - (level + 1)) + 1 by omega,
            pow_succ]
          ring

theorem card_adicPower_zero_le_pow_mul
    {R : Type} [CommRing R] [Fintype R]
    (residue : R →+* ZMod 2) (uniformizer : R)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (level : ℕ) :
    Nat.card (adicPower uniformizer 0) ≤
      2 ^ level * Nat.card (adicPower uniformizer level) := by
  induction level with
  | zero => simp
  | succ level ih =>
      calc
        Nat.card (adicPower uniformizer 0) ≤
            2 ^ level * Nat.card (adicPower uniformizer level) := ih
        _ ≤ 2 ^ level *
            (2 * Nat.card (adicPower uniformizer (level + 1))) :=
          Nat.mul_le_mul_left _
            (card_adicPower_le_two_mul_succ residue uniformizer hker level)
        _ = 2 ^ (level + 1) * Nat.card (adicPower uniformizer (level + 1)) := by
          rw [pow_succ]
          ring

theorem adicPower_zero_eq_top {R : Type} [CommRing R] (uniformizer : R) :
    adicPower uniformizer 0 = ⊤ := by
  ext value
  constructor
  · intro
    trivial
  · intro
    exact ⟨value, by simp [rightMulAddHom]⟩

theorem card_adicPower_eq_pow_sub
    {R : Type} [CommRing R] [Fintype R]
    (residue : R →+* ZMod 2) (uniformizer : R) (length : ℕ)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (hzero : uniformizer ^ length = 0)
    (hcard : Nat.card R = 2 ^ length)
    (level : ℕ) (hlevel : level ≤ length) :
    Nat.card (adicPower uniformizer level) = 2 ^ (length - level) := by
  apply le_antisymm
  · exact card_adicPower_le_pow_sub residue uniformizer length hker hzero level hlevel
  · have hprefix := card_adicPower_zero_le_pow_mul
        residue uniformizer hker level
    rw [adicPower_zero_eq_top uniformizer, AddSubgroup.card_top, hcard] at hprefix
    have hfactor : 2 ^ length = 2 ^ level * 2 ^ (length - level) := by
      rw [← pow_add]
      congr 1
      omega
    rw [hfactor] at hprefix
    exact Nat.le_of_mul_le_mul_left hprefix (by positivity)

theorem truncatedValuation_eq_length_of_eq_zero
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (uniformizer : R) (length : ℕ) :
    truncatedValuation uniformizer length 0 = length := by
  classical
  unfold truncatedValuation
  apply Nat.findGreatest_eq
  exact AddSubgroup.zero_mem _

theorem truncatedValuation_lt_of_ne_zero
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (uniformizer : R) (length : ℕ)
    (hzero : uniformizer ^ length = 0)
    (value : R) (hvalue : value ≠ 0) :
    truncatedValuation uniformizer length value < length := by
  apply lt_of_le_of_ne
    (truncatedValuation_le uniformizer length value)
  intro heq
  have hmem := mem_adicPower_truncatedValuation uniformizer length value
  rw [heq, adicPower_eq_bot_of_pow_eq_zero uniformizer length hzero] at hmem
  exact hvalue (by simpa using hmem)

theorem factor_at_truncatedValuation_isUnit
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (residue : R →+* ZMod 2) [IsLocalHom residue]
    (uniformizer : R) (length : ℕ)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (hzero : uniformizer ^ length = 0)
    (value : R) (hvalue : value ≠ 0) :
    ∃ factor : R,
      factor * uniformizer ^ truncatedValuation uniformizer length value = value ∧
        IsUnit factor := by
  classical
  let level := truncatedValuation uniformizer length value
  have hlevel : level < length :=
    truncatedValuation_lt_of_ne_zero uniformizer length hzero value hvalue
  have hmem := mem_adicPower_truncatedValuation uniformizer length value
  obtain ⟨factor, hfactor⟩ := hmem
  refine ⟨factor, hfactor, ?_⟩
  have hresidue_ne : residue factor ≠ 0 := by
    intro hresidue
    have hfactorKer : factor ∈ RingHom.ker residue := RingHom.mem_ker.mpr hresidue
    have hfactorKerAdd : factor ∈ (RingHom.ker residue).toAddSubgroup := hfactorKer
    rw [hker] at hfactorKerAdd
    obtain ⟨next, hnext⟩ := hfactorKerAdd
    have hvalueSucc : value ∈ adicPower uniformizer (level + 1) := by
      refine ⟨next, ?_⟩
      simp only [rightMulAddHom_apply] at hfactor hnext ⊢
      rw [← hfactor, ← hnext, pow_succ]
      ring
    exact Nat.findGreatest_is_greatest
      (P := fun candidate ↦ value ∈ adicPower uniformizer candidate)
      (show truncatedValuation uniformizer length value < level + 1 by
        simp [level])
      (by omega) hvalueSucc
  have hresidue_one : residue factor = 1 :=
    (zmodTwo_eq_zero_or_one (residue factor)).resolve_left hresidue_ne
  exact isUnit_of_map_unit residue factor (by rw [hresidue_one]; exact isUnit_one)

theorem rightMulRange_eq_adicPower_truncatedValuation
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (residue : R →+* ZMod 2) [IsLocalHom residue]
    (uniformizer : R) (length : ℕ)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (hzero : uniformizer ^ length = 0)
    (value : R) :
    (rightMulAddHom value).range =
      adicPower uniformizer (truncatedValuation uniformizer length value) := by
  classical
  by_cases hvalue : value = 0
  · subst value
    rw [truncatedValuation_eq_length_of_eq_zero uniformizer length,
      adicPower_eq_bot_of_pow_eq_zero uniformizer length hzero]
    ext target
    constructor
    · rintro ⟨multiplier, hmultiplier⟩
      simp only [rightMulAddHom_apply, mul_zero] at hmultiplier
      subst target
      exact AddSubgroup.zero_mem _
    · intro htarget
      have : target = 0 := by simpa using htarget
      subst target
      exact ⟨0, by simp⟩
  · obtain ⟨factor, hfactor, hfactorUnit⟩ :=
      factor_at_truncatedValuation_isUnit
        residue uniformizer length hker hzero value hvalue
    obtain ⟨unit, hunit⟩ := hfactorUnit
    ext target
    constructor
    · rintro ⟨multiplier, hmultiplier⟩
      refine ⟨multiplier * factor, ?_⟩
      simp only [rightMulAddHom_apply] at hfactor hmultiplier ⊢
      calc
        multiplier * factor *
            uniformizer ^ truncatedValuation uniformizer length value =
            multiplier *
              (factor * uniformizer ^ truncatedValuation uniformizer length value) := by ring
        _ = multiplier * value := by rw [hfactor]
        _ = target := hmultiplier
    · rintro ⟨multiplier, hmultiplier⟩
      refine ⟨multiplier * ↑(unit⁻¹), ?_⟩
      simp only [rightMulAddHom_apply] at hfactor hmultiplier ⊢
      calc
        multiplier * ↑(unit⁻¹) * value =
            multiplier * (↑(unit⁻¹) * value) := by ring
        _ = multiplier *
            (↑(unit⁻¹) *
              (factor * uniformizer ^ truncatedValuation uniformizer length value)) := by
                rw [hfactor]
        _ = multiplier * uniformizer ^ truncatedValuation uniformizer length value := by
          rw [← hunit]
          simp
        _ = target := hmultiplier

theorem mem_adicPower_of_le_truncatedValuation
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (uniformizer : R) (length : ℕ) (value : R) {level : ℕ}
    (hle : level ≤ truncatedValuation uniformizer length value) :
    value ∈ adicPower uniformizer level :=
  adicPower_antitone uniformizer hle
    (mem_adicPower_truncatedValuation uniformizer length value)

theorem everyIdeal_eq_adicPower
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (residue : R →+* ZMod 2) [IsLocalHom residue]
    (uniformizer : R) (length : ℕ)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (hzero : uniformizer ^ length = 0)
    (ideal : Ideal R) :
    ∃ level ≤ length, ideal.toAddSubgroup = adicPower uniformizer level := by
  classical
  by_cases hideal : ideal = ⊥
  · refine ⟨length, le_rfl, ?_⟩
    rw [hideal, adicPower_eq_bot_of_pow_eq_zero uniformizer length hzero]
    rfl
  · have hexists : ∃ level : ℕ, ∃ value : R,
        value ∈ ideal ∧ value ≠ 0 ∧
          truncatedValuation uniformizer length value = level := by
      obtain ⟨value, hvalueIdeal, hvalue⟩ :=
        SetLike.exists_of_lt (bot_lt_iff_ne_bot.mpr hideal : ⊥ < ideal)
      exact ⟨truncatedValuation uniformizer length value,
        value, hvalueIdeal, hvalue, rfl⟩
    let level := Nat.find hexists
    obtain ⟨generator, hgeneratorIdeal, hgenerator, hgeneratorLevel⟩ :=
      Nat.find_spec hexists
    have hlevel : level ≤ length := by
      change Nat.find hexists ≤ length
      rw [← hgeneratorLevel]
      exact truncatedValuation_le uniformizer length generator
    refine ⟨level, hlevel, ?_⟩
    apply le_antisymm
    · intro value hvalueIdeal
      by_cases hvalue : value = 0
      · subst value
        exact AddSubgroup.zero_mem _
      · have hminimal : level ≤
            truncatedValuation uniformizer length value := by
          apply Nat.find_min' hexists
          exact ⟨value, hvalueIdeal, hvalue, rfl⟩
        exact mem_adicPower_of_le_truncatedValuation
          uniformizer length value hminimal
    · intro value hvaluePower
      change value ∈ adicPower uniformizer (Nat.find hexists) at hvaluePower
      rw [← hgeneratorLevel,
        ← rightMulRange_eq_adicPower_truncatedValuation
          residue uniformizer length hker hzero generator] at hvaluePower
      obtain ⟨multiplier, hmultiplier⟩ := hvaluePower
      simp only [rightMulAddHom_apply] at hmultiplier
      rw [← hmultiplier]
      exact ideal.mul_mem_left multiplier hgeneratorIdeal

def finiteAdicChainOfPrincipalResidue
    {R : Type} [CommRing R] [Fintype R] [DecidableEq R]
    (residue : R →+* ZMod 2) [IsLocalHom residue]
    (uniformizer : R) (length : ℕ)
    (hker : (RingHom.ker residue).toAddSubgroup = adicPower uniformizer 1)
    (hzero : uniformizer ^ length = 0)
    (hcard : Nat.card R = 2 ^ length) : FiniteAdicChain R where
  uniformizer := uniformizer
  length := length
  valuation := truncatedValuation uniformizer length
  valuation_le := truncatedValuation_le uniformizer length
  principal_eq := rightMulRange_eq_adicPower_truncatedValuation
    residue uniformizer length hker hzero
  card_ring := hcard
  card_power := card_adicPower_eq_pow_sub
    residue uniformizer length hker hzero hcard
  idealChain := everyIdeal_eq_adicPower
    residue uniformizer length hker hzero

open Polynomial
open FormalProof4FHE.RLWE
open FormalProof4FHE.TFHE.Native.ShiftedCandidateEvaluator.DiagonalNormalForm
open FormalProof4FHE.TFHE.Native.PowerOfTwoLocalRing

noncomputable instance quotientPowerOfTwoRqFintype
    (modulusExponent degreeExponent : ℕ) [hmodulus : Fact (0 < modulusExponent)] :
    Fintype (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) := by
  letI : Fact (1 < 2 ^ modulusExponent) :=
    ⟨one_lt_pow' (by omega : 1 < 2) (Nat.ne_of_gt hmodulus.out)⟩
  exact Fintype.ofEquiv
    (Rq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (quotientEquiv
      (q := 2 ^ modulusExponent) (pow_pos (by omega : 0 < 2) degreeExponent))

noncomputable instance quotientPowerOfTwoRqDecidableEq
    (modulusExponent degreeExponent : ℕ) [Fact (0 < modulusExponent)] :
    DecidableEq (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) :=
  Classical.decEq _

noncomputable def quotientUniformizer (q degree : ℕ) : QuotientRq q degree :=
  Ideal.Quotient.mk _ (C 1 - X)

noncomputable def quotientGeomSum (q degree : ℕ) : QuotientRq q degree :=
  Ideal.Quotient.mk _ (∑ index ∈ Finset.range degree, (X : Polynomial (ZMod q)) ^ index)

theorem quotientUniformizer_mul_geomSum (q degree : ℕ) :
    quotientUniformizer q degree * quotientGeomSum q degree = 2 := by
  change Ideal.Quotient.mk _ (C 1 - X) *
      Ideal.Quotient.mk _ (∑ index ∈ Finset.range degree,
        (X : Polynomial (ZMod q)) ^ index) =
    Ideal.Quotient.mk _ (C (2 : ZMod q))
  rw [← map_mul, Ideal.Quotient.mk_eq_mk_iff_sub_mem,
    Ideal.mem_span_singleton]
  refine ⟨-1, ?_⟩
  have hgeom : (∑ index ∈ Finset.range degree,
      (X : Polynomial (ZMod q)) ^ index) * (X - 1) = X ^ degree - 1 :=
    geom_sum_mul (X : Polynomial (ZMod q)) degree
  simp only [LatticeCrypto.negacyclicModulus, map_one, map_ofNat]
  linear_combination -hgeom

theorem quotientParityEval_uniformizer
    {q degree : ℕ} (heven : 2 ∣ q) :
    quotientParityEval heven (quotientUniformizer q degree) = 0 := by
  simp [quotientUniformizer, quotientParityEval, polynomialParityEval]

theorem zmod_powerOfTwo_exists_two_mul_eq_of_castHom_eq_zero
    (modulusExponent : ℕ) (modulusExponent_positive : 0 < modulusExponent)
    (value : ZMod (2 ^ modulusExponent))
    (parity_zero :
      ZMod.castHom (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) (ZMod 2) value = 0) :
    ∃ half : ZMod (2 ^ modulusExponent), 2 * half = value := by
  letI : NeZero (2 ^ modulusExponent) :=
    ⟨pow_ne_zero modulusExponent (by omega)⟩
  have value_even : 2 ∣ value.val := by
    rw [ZMod.castHom_apply, ZMod.cast_eq_val] at parity_zero
    exact (CharP.cast_eq_zero_iff (ZMod 2) 2 value.val).mp parity_zero
  obtain ⟨half, value_val_eq⟩ := value_even
  refine ⟨(half : ZMod (2 ^ modulusExponent)), ?_⟩
  calc
    (2 : ZMod (2 ^ modulusExponent)) * half =
        (2 * half : ℕ) := by norm_num
    _ = (value.val : ZMod (2 ^ modulusExponent)) := by rw [value_val_eq]
    _ = value := value.natCast_zmod_val

theorem polynomial_C_two_dvd_of_map_castHom_eq_zero
    (modulusExponent : ℕ) (modulusExponent_positive : 0 < modulusExponent)
    (polynomial : Polynomial (ZMod (2 ^ modulusExponent)))
    (mapped_zero : polynomial.map
      (ZMod.castHom (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) (ZMod 2)) = 0) :
    C (2 : ZMod (2 ^ modulusExponent)) ∣ polynomial := by
  rw [Polynomial.C_dvd_iff_dvd_coeff]
  intro coefficient
  have hcoefficient := congrArg
    (fun mapped : Polynomial (ZMod 2) ↦ mapped.coeff coefficient) mapped_zero
  have hparity :
      ZMod.castHom (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) (ZMod 2)
        (polynomial.coeff coefficient) = 0 := by
    simpa using hcoefficient
  obtain ⟨half, hhalf⟩ :=
    zmod_powerOfTwo_exists_two_mul_eq_of_castHom_eq_zero
      modulusExponent modulusExponent_positive _ hparity
  exact ⟨half, hhalf.symm⟩

theorem quotientParityEval_ker_eq_uniformizer_powerOfTwo
    (modulusExponent : ℕ) (modulusExponent_positive : 0 < modulusExponent)
    (degree : ℕ) :
    (RingHom.ker
      (quotientParityEval
        (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) :
          QuotientRq (2 ^ modulusExponent) degree →+* ZMod 2)).toAddSubgroup =
      adicPower (quotientUniformizer (2 ^ modulusExponent) degree) 1 := by
  classical
  let coefficientReduce : ZMod (2 ^ modulusExponent) →+* ZMod 2 :=
    ZMod.castHom (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) (ZMod 2)
  apply le_antisymm
  · intro value hvalue
    obtain ⟨polynomial, rfl⟩ := Ideal.Quotient.mk_surjective value
    have parity_zero : polynomialParityEval
        (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) polynomial = 0 := by
      change quotientParityEval
        (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent))
          (Ideal.Quotient.mk _ polynomial) = 0 at hvalue
      simpa only [quotientParityEval, Ideal.Quotient.lift_mk] using hvalue
    have eval_zero : Polynomial.eval 1 (polynomial.map coefficientReduce) = 0 := by
      simpa [polynomialParityEval, coefficientReduce] using parity_zero
    have polynomial_mem : polynomial.map coefficientReduce ∈
        Ideal.span {X - C (1 : ZMod 2)} := by
      rw [← Polynomial.ker_evalRingHom]
      exact RingHom.mem_ker.mpr eval_zero
    obtain ⟨binaryFactor, mapped_polynomial_eq⟩ :=
      Ideal.mem_span_singleton.mp polynomial_mem
    obtain ⟨liftedFactor, liftedFactor_spec⟩ :=
      Polynomial.map_surjective coefficientReduce
        (ZMod.castHom_surjective
          (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent))) binaryFactor
    let remainder : Polynomial (ZMod (2 ^ modulusExponent)) :=
      polynomial - (X - C 1) * liftedFactor
    have remainder_map : remainder.map coefficientReduce = 0 := by
      dsimp only [remainder]
      rw [Polynomial.map_sub, Polynomial.map_mul,
        liftedFactor_spec, mapped_polynomial_eq]
      simp [coefficientReduce]
    obtain ⟨evenFactor, evenFactor_spec⟩ :=
      polynomial_C_two_dvd_of_map_castHom_eq_zero
        modulusExponent modulusExponent_positive remainder remainder_map
    have polynomial_eq :
        polynomial = (X - C 1) * liftedFactor + C 2 * evenFactor := by
      dsimp only [remainder] at evenFactor_spec
      linear_combination evenFactor_spec
    let quotientLifted : QuotientRq (2 ^ modulusExponent) degree :=
      Ideal.Quotient.mk _ liftedFactor
    let quotientEven : QuotientRq (2 ^ modulusExponent) degree :=
      Ideal.Quotient.mk _ evenFactor
    let uniformizer := quotientUniformizer (2 ^ modulusExponent) degree
    let geom := quotientGeomSum (2 ^ modulusExponent) degree
    refine ⟨-quotientLifted + geom * quotientEven, ?_⟩
    simp only [rightMulAddHom_apply, pow_one]
    change (-quotientLifted + geom * quotientEven) * uniformizer =
      Ideal.Quotient.mk _ polynomial
    rw [polynomial_eq, map_add, map_mul, map_mul]
    have hfirst : Ideal.Quotient.mk
        (Ideal.span {LatticeCrypto.negacyclicModulus
          (ZMod (2 ^ modulusExponent)) degree}) (X - C 1) = -uniformizer := by
      dsimp only [uniformizer, quotientUniformizer]
      simp only [map_sub, map_one]
      ring
    have htwo : Ideal.Quotient.mk
        (Ideal.span {LatticeCrypto.negacyclicModulus
          (ZMod (2 ^ modulusExponent)) degree}) (C 2) = uniformizer * geom := by
      dsimp only [uniformizer, geom]
      simpa only [map_ofNat] using
        (quotientUniformizer_mul_geomSum
          (2 ^ modulusExponent) degree).symm
    rw [hfirst, htwo]
    ring
  · intro value hvalue
    obtain ⟨multiplier, hmultiplier⟩ := hvalue
    apply RingHom.mem_ker.mpr
    rw [← hmultiplier]
    change quotientParityEval
      (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent))
        (multiplier * quotientUniformizer (2 ^ modulusExponent) degree ^ 1) = 0
    rw [map_mul, map_pow,
      quotientParityEval_uniformizer,
      zero_pow (by omega : 1 ≠ 0), mul_zero]

theorem quotientCoefficientReduce_uniformizer
    {q degree : ℕ} (heven : 2 ∣ q) :
    quotientCoefficientReduce heven (quotientUniformizer q degree) =
      quotientUniformizer 2 degree := by
  unfold quotientUniformizer
  rw [quotientCoefficientReduce_mk]
  simp

theorem quotientUniformizer_pow_eq_zero_binary_powerOfTwo
    (degreeExponent : ℕ) :
    quotientUniformizer 2 (2 ^ degreeExponent) ^ (2 ^ degreeExponent) = 0 := by
  rw [show quotientUniformizer 2 (2 ^ degreeExponent) ^ (2 ^ degreeExponent) =
      Ideal.Quotient.mk _
        ((C 1 - X : Polynomial (ZMod 2)) ^ (2 ^ degreeExponent)) by
      simp [quotientUniformizer]]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  rw [binary_negacyclicModulus_eq_X_sub_one_pow,
    Ideal.mem_span_singleton]
  refine ⟨(-1 : Polynomial (ZMod 2)) ^ (2 ^ degreeExponent), ?_⟩
  rw [show (C 1 - X : Polynomial (ZMod 2)) = -(X - C 1) by ring,
    neg_pow]
  exact mul_comm _ _

theorem quotientUniformizer_pow_reduces_to_zero
    (modulusExponent : ℕ) (modulusExponent_positive : 0 < modulusExponent)
    (degreeExponent : ℕ) :
    quotientCoefficientReduce
        (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent))
        (quotientUniformizer (2 ^ modulusExponent) (2 ^ degreeExponent) ^
          (2 ^ degreeExponent)) = 0 := by
  rw [map_pow, quotientCoefficientReduce_uniformizer,
    quotientUniformizer_pow_eq_zero_binary_powerOfTwo]

theorem quotientCoefficientReduce_exists_two_mul_eq_powerOfTwo
    (modulusExponent : ℕ) (modulusExponent_positive : 0 < modulusExponent)
    (degree : ℕ)
    (value : QuotientRq (2 ^ modulusExponent) degree)
    (reduction_zero :
      quotientCoefficientReduce
        (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) value = 0) :
    ∃ half : QuotientRq (2 ^ modulusExponent) degree, 2 * half = value := by
  let coefficientReduce : ZMod (2 ^ modulusExponent) →+* ZMod 2 :=
    ZMod.castHom (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent)) (ZMod 2)
  obtain ⟨polynomial, rfl⟩ := Ideal.Quotient.mk_surjective value
  rw [quotientCoefficientReduce_mk,
    Ideal.Quotient.eq_zero_iff_mem,
    Ideal.mem_span_singleton] at reduction_zero
  obtain ⟨binaryFactor, mapped_polynomial_eq⟩ := reduction_zero
  obtain ⟨liftedFactor, liftedFactor_spec⟩ :=
    Polynomial.map_surjective coefficientReduce
      (ZMod.castHom_surjective
        (pow_dvd_pow 2 (by omega : 1 ≤ modulusExponent))) binaryFactor
  let remainder : Polynomial (ZMod (2 ^ modulusExponent)) :=
    polynomial -
      LatticeCrypto.negacyclicModulus
        (ZMod (2 ^ modulusExponent)) degree * liftedFactor
  have modulus_map :
      (LatticeCrypto.negacyclicModulus
          (ZMod (2 ^ modulusExponent)) degree).map coefficientReduce =
        LatticeCrypto.negacyclicModulus (ZMod 2) degree := by
    simp [coefficientReduce, LatticeCrypto.negacyclicModulus]
  have remainder_map : remainder.map coefficientReduce = 0 := by
    dsimp only [remainder]
    rw [Polynomial.map_sub, Polynomial.map_mul, modulus_map,
      liftedFactor_spec, mapped_polynomial_eq, sub_self]
  obtain ⟨halfPolynomial, halfPolynomial_spec⟩ :=
    polynomial_C_two_dvd_of_map_castHom_eq_zero
      modulusExponent modulusExponent_positive remainder remainder_map
  refine ⟨Ideal.Quotient.mk _ halfPolynomial, ?_⟩
  have quotient_eq :
      Ideal.Quotient.mk
          (Ideal.span {LatticeCrypto.negacyclicModulus
            (ZMod (2 ^ modulusExponent)) degree}) polynomial =
        Ideal.Quotient.mk
          (Ideal.span {LatticeCrypto.negacyclicModulus
            (ZMod (2 ^ modulusExponent)) degree}) remainder := by
    dsimp only [remainder]
    simp [map_sub, map_mul]
  rw [quotient_eq, halfPolynomial_spec]
  simp only [map_mul, map_ofNat]

theorem quotientUniformizer_pow_length_eq_zero
    (modulusExponent : ℕ) (modulusExponent_positive : 0 < modulusExponent)
    (degreeExponent : ℕ) :
    quotientUniformizer (2 ^ modulusExponent) (2 ^ degreeExponent) ^
        (modulusExponent * 2 ^ degreeExponent) = 0 := by
  obtain ⟨half, hhalf⟩ :=
    quotientCoefficientReduce_exists_two_mul_eq_powerOfTwo
      modulusExponent modulusExponent_positive (2 ^ degreeExponent)
      (quotientUniformizer (2 ^ modulusExponent) (2 ^ degreeExponent) ^
        (2 ^ degreeExponent))
      (quotientUniformizer_pow_reduces_to_zero
        modulusExponent modulusExponent_positive degreeExponent)
  rw [Nat.mul_comm, pow_mul, ← hhalf, mul_pow]
  have htwo :
      (2 : QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) ^
          modulusExponent = 0 := by
    have hcoefficient :
        (2 : ZMod (2 ^ modulusExponent)) ^ modulusExponent = 0 := by
      calc
        (2 : ZMod (2 ^ modulusExponent)) ^ modulusExponent =
            ((2 ^ modulusExponent : ℕ) : ZMod (2 ^ modulusExponent)) := by
          exact (Nat.cast_pow 2 modulusExponent).symm
        _ = 0 := ZMod.natCast_self (2 ^ modulusExponent)
    change (Ideal.Quotient.mk _
      (C (2 : ZMod (2 ^ modulusExponent)))) ^ modulusExponent = 0
    rw [← map_pow (Ideal.Quotient.mk _) _ modulusExponent,
      ← Polynomial.C_pow, hcoefficient]
    simp
  rw [htwo, zero_mul]

theorem card_quotientPowerOfTwoRq
    (modulusExponent degreeExponent : ℕ) [hmodulus : Fact (0 < modulusExponent)] :
    Nat.card (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) =
      2 ^ (modulusExponent * 2 ^ degreeExponent) := by
  letI : Fact (1 < 2 ^ modulusExponent) :=
    ⟨one_lt_pow' (by omega : 1 < 2) (Nat.ne_of_gt hmodulus.out)⟩
  calc
    Nat.card (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) =
        Nat.card (Rq (2 ^ modulusExponent) (2 ^ degreeExponent)) :=
      Nat.card_congr
        (quotientEquiv
          (q := 2 ^ modulusExponent)
          (pow_pos (by omega : 0 < 2) degreeExponent)).symm
    _ = Fintype.card (Rq (2 ^ modulusExponent) (2 ^ degreeExponent)) :=
      Nat.card_eq_fintype_card
    _ = 2 ^ (modulusExponent * 2 ^ degreeExponent) :=
      card_powerOfTwoRq modulusExponent degreeExponent

noncomputable def quotientPowerOfTwoAdicChain
    (modulusExponent degreeExponent : ℕ) [hmodulus : Fact (0 < modulusExponent)] :
    FiniteAdicChain
      (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) := by
  classical
  let residue : QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent) →+* ZMod 2 :=
    quotientParityEval
      (pow_dvd_pow 2 (Nat.succ_le_iff.mpr hmodulus.out))
  letI : IsLocalHom residue :=
    isLocalHom_toZModTwo_of_nilpotent_kernel residue (by
      intro value hvalue
      exact quotientParityEval_kernel_isNilpotent_powerOfTwo
        modulusExponent hmodulus.out degreeExponent value hvalue)
  exact finiteAdicChainOfPrincipalResidue
    residue
    (quotientUniformizer (2 ^ modulusExponent) (2 ^ degreeExponent))
    (modulusExponent * 2 ^ degreeExponent)
    (quotientParityEval_ker_eq_uniformizer_powerOfTwo
      modulusExponent hmodulus.out (2 ^ degreeExponent))
    (quotientUniformizer_pow_length_eq_zero
      modulusExponent hmodulus.out degreeExponent)
    (card_quotientPowerOfTwoRq
      modulusExponent degreeExponent)

/-! ## Literal power-of-two statistical theorems -/

/-- The chain certificate has exactly the ramification length from the paper. -/
@[simp]
theorem quotientPowerOfTwoAdicChain_length
    (modulusExponent degreeExponent : ℕ) [Fact (0 < modulusExponent)] :
    (quotientPowerOfTwoAdicChain modulusExponent degreeExponent).length =
      modulusExponent * 2 ^ degreeExponent := rfl

/-- Any value whose parity residue vanishes lies at least in the first ramified layer.  This is
the algebraic fact used by the paper's even-weight ternary-secret observation. -/
theorem one_le_quotientPowerOfTwoAdicChain_valuation_of_parity_zero
    (modulusExponent degreeExponent : ℕ) [hmodulus : Fact (0 < modulusExponent)]
    (value : QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (hparity :
      quotientParityEval
          (pow_dvd_pow 2 (Nat.succ_le_iff.mpr hmodulus.out)) value = 0) :
    1 ≤ (quotientPowerOfTwoAdicChain
      modulusExponent degreeExponent).valuation value := by
  classical
  let uniformizer := quotientUniformizer
    (2 ^ modulusExponent) (2 ^ degreeExponent)
  have hmemKer : value ∈ RingHom.ker
      (quotientParityEval
        (pow_dvd_pow 2 (Nat.succ_le_iff.mpr hmodulus.out)) :
          QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent) →+* ZMod 2) :=
    RingHom.mem_ker.mpr hparity
  have hmemPower : value ∈ adicPower uniformizer 1 := by
    have hmemKerAdd : value ∈
        (RingHom.ker
          (quotientParityEval
            (pow_dvd_pow 2 (Nat.succ_le_iff.mpr hmodulus.out)) :
              QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent) →+* ZMod 2)).toAddSubgroup :=
      hmemKer
    rw [quotientParityEval_ker_eq_uniformizer_powerOfTwo
      modulusExponent hmodulus.out (2 ^ degreeExponent)] at hmemKerAdd
    exact hmemKerAdd
  change 1 ≤ truncatedValuation uniformizer
    (modulusExponent * 2 ^ degreeExponent) value
  apply Nat.le_findGreatest
  · exact Nat.succ_le_iff.mpr (Nat.mul_pos hmodulus.out (pow_pos (by omega) _))
  · exact hmemPower

/-- Direct quadratic KDM rows over the literal semantic power-of-two quotient are bounded by
the exact `pi`-adic collision moment. -/
theorem tvDist_quadratic_ideal_le_literalPowerOfTwo
    (modulusExponent degreeExponent : ℕ) [Fact (0 < modulusExponent)]
    {Seed Side Row : Type}
    [Fintype Seed] [Nonempty Seed] [Fintype Side] [Fintype Row]
    [DecidableEq Side] [DecidableEq Row]
    [SampleableType
      (Seed × (Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)))]
    [SampleableType
      (QuadraticKDM.TargetTranscript
        (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) Row)]
    (secret : Seed → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (error : Seed → Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (leakage : Seed → Side)
    (weight : Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineIdealSampler
          (R := QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
          (Row := Row) leakage) ≤
      Real.sqrt
        (powerOfTwoTheta
          (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
          secret error leakage - 1) / 2 :=
  tvDist_quadratic_ideal_le_powerOfTwoTheta
    (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
    secret error leakage weight

/-- The corresponding zero-message rows obey the same literal-ring bound. -/
theorem tvDist_zero_ideal_le_literalPowerOfTwo
    (modulusExponent degreeExponent : ℕ) [Fact (0 < modulusExponent)]
    {Seed Side Row : Type}
    [Fintype Seed] [Nonempty Seed] [Fintype Side] [Fintype Row]
    [DecidableEq Side] [DecidableEq Row]
    [SampleableType
      (Seed × (Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)))]
    [SampleableType
      (QuadraticKDM.TargetTranscript
        (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) Row)]
    (secret : Seed → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (error : Seed → Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (leakage : Seed → Side) :
    tvDist
        (affineJointSampler secret error leakage
          (fun (_leakage : Side) (_row : Row)
            (_value : QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) ↦ 0))
        (affineIdealSampler
          (R := QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
          (Row := Row) leakage) ≤
      Real.sqrt
        (powerOfTwoTheta
          (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
          secret error leakage - 1) / 2 :=
  tvDist_zero_ideal_le_powerOfTwoTheta
    (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
    secret error leakage

/-- Quadratic and zero-message rows over the literal quotient are at most the full square-root
moment apart. -/
theorem tvDist_quadratic_zero_le_literalPowerOfTwo
    (modulusExponent degreeExponent : ℕ) [Fact (0 < modulusExponent)]
    {Seed Side Row : Type}
    [Fintype Seed] [Nonempty Seed] [Fintype Side] [Fintype Row]
    [DecidableEq Side] [DecidableEq Row]
    [SampleableType
      (Seed × (Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)))]
    [SampleableType
      (QuadraticKDM.TargetTranscript
        (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) Row)]
    (secret : Seed → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (error : Seed → Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (leakage : Seed → Side)
    (weight : Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineJointSampler secret error leakage
          (fun (_leakage : Side) (_row : Row)
            (_value : QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) ↦ 0)) ≤
      Real.sqrt
        (powerOfTwoTheta
          (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
          secret error leakage - 1) :=
  tvDist_quadratic_zero_le_powerOfTwoTheta
    (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
    secret error leakage weight

/-- The paper's numerical criterion `Theta ≤ 1 + 4*epsilon^2`, now with no remaining
chain-ring premise for the literal quotient. -/
theorem tvDist_quadratic_ideal_le_epsilon_literalPowerOfTwo
    (modulusExponent degreeExponent : ℕ) [Fact (0 < modulusExponent)]
    {Seed Side Row : Type}
    [Fintype Seed] [Nonempty Seed] [Fintype Side] [Fintype Row]
    [DecidableEq Side] [DecidableEq Row]
    [SampleableType
      (Seed × (Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)))]
    [SampleableType
      (QuadraticKDM.TargetTranscript
        (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) Row)]
    (secret : Seed → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (error : Seed → Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (leakage : Seed → Side)
    (weight : Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (epsilon : ℝ) (hepsilon : 0 ≤ epsilon)
    (htheta :
      powerOfTwoTheta
          (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
          secret error leakage ≤
        1 + 4 * epsilon ^ 2) :
    tvDist
        (affineJointSampler secret error leakage
          (fun _leakage row value ↦ weight row * value ^ 2))
        (affineIdealSampler
          (R := QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
          (Row := Row) leakage) ≤ epsilon :=
  tvDist_quadratic_ideal_le_epsilon
    (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
    secret error leakage weight epsilon hepsilon htheta

/-- Literal-ring specialization of the correlated HNF/masked-quadratic statistical theorem. -/
theorem tvDist_maskedQuadratic_ideal_le_literalPowerOfTwo
    (modulusExponent degreeExponent : ℕ) [Fact (0 < modulusExponent)]
    {Seed Side Row : Type}
    [Fintype Seed] [Nonempty Seed] [Fintype Side] [Fintype Row]
    [DecidableEq Side] [DecidableEq Row]
    [SampleableType
      (Seed × (Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)))]
    [SampleableType
      (QuadraticKDM.TargetTranscript
        (QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) Row)]
    (secret : Seed → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (error : Seed → Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (leakage : Seed → Side)
    (proofMask : Side → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
    (weight : Row → QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent)) :
    tvDist
        (affineJointSampler secret error leakage
          (fun leakageValue row value ↦
            weight row * (value - proofMask leakageValue) ^ 2))
        (affineIdealSampler
          (R := QuotientRq (2 ^ modulusExponent) (2 ^ degreeExponent))
          (Row := Row) leakage) ≤
      Real.sqrt
        (powerOfTwoTheta
          (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
          secret error leakage - 1) / 2 :=
  tvDist_maskedQuadratic_ideal_le_powerOfTwoTheta
    (quotientPowerOfTwoAdicChain modulusExponent degreeExponent)
    secret error leakage proofMask weight

end

end FormalProof4FHE.RLWE.PowerOfTwoQuadraticKDMStatistical
