/-
Copyright (c) 2026 Kotaro Matsuoka. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Kotaro Matsuoka
-/

import FormalProof4FHE.RLWE.Basic
import Mathlib.RingTheory.Polynomial.Cyclotomic.Basic

/-!
# Power-of-Two Cyclotomic Identification for Negacyclic RLWE

The executable RLWE carrier is interpreted in the quotient by `X^N + 1`.  Foundational RLWE
results for the usual power-of-two cyclotomic family instead name the quotient by the cyclotomic
polynomial `Φ_(2N)`.  These presentations agree exactly when `N` is a power of two.

This module proves the polynomial identity and packages the induced quotient-ring equivalence.
It is an algebraic representation bridge only: it does not import a computational hardness
theorem, identify coefficient and canonical embeddings, or change an error distribution.
-/

open Polynomial

namespace FormalProof4FHE.RLWE.PowerOfTwoCyclotomic

/-- Quotient by the `index`-th cyclotomic polynomial over `R`. -/
abbrev CyclotomicQuotient (R : Type*) [CommRing R] (index : ℕ) :=
  Polynomial R ⧸
    Ideal.span ({cyclotomic index R} : Set (Polynomial R))

/-- For every coefficient ring, the cyclotomic polynomial of order `2^(k+1)` is
`X^(2^k) + 1`. -/
theorem cyclotomic_two_pow_succ_eq {R : Type*} [CommRing R] (exponent : ℕ) :
    cyclotomic (2 ^ (exponent + 1)) R = X ^ (2 ^ exponent) + 1 := by
  rw [cyclotomic_prime_pow_eq_geom_sum (R := R) Nat.prime_two]
  simp [Finset.sum_range_succ, add_comm]

/-- The ideal defining the degree-`2^k` negacyclic quotient is exactly the ideal generated by
the order-`2^(k+1)` cyclotomic polynomial. -/
theorem negacyclicIdeal_eq_cyclotomicIdeal {R : Type*} [CommRing R] (exponent : ℕ) :
    Ideal.span
        ({LatticeCrypto.negacyclicModulus R (2 ^ exponent)} : Set (Polynomial R)) =
      Ideal.span ({cyclotomic (2 ^ (exponent + 1)) R} : Set (Polynomial R)) := by
  rw [cyclotomic_two_pow_succ_eq]
  rfl

/-- The semantic degree-`2^k` negacyclic quotient is literally the corresponding
power-of-two cyclotomic quotient, up to the canonical quotient-by-equal-ideals equivalence. -/
noncomputable def quotientEquivCyclotomic {R : Type*} [CommRing R] (exponent : ℕ) :
    LatticeCrypto.NegacyclicQuotient R (2 ^ exponent) ≃+*
      CyclotomicQuotient R (2 ^ (exponent + 1)) := by
  unfold LatticeCrypto.NegacyclicQuotient
  exact Ideal.quotEquivOfEq (negacyclicIdeal_eq_cyclotomicIdeal exponent)

/-- Interpret an executable degree-`2^k` negacyclic polynomial directly in the corresponding
cyclotomic quotient. -/
noncomputable def executableToCyclotomic (q exponent : ℕ)
    (value : Rq q (2 ^ exponent)) :
    CyclotomicQuotient (ZMod q) (2 ^ (exponent + 1)) :=
  quotientEquivCyclotomic exponent
    (quotientOf (Nat.two_pow_pos exponent) value)

/-- The executable-to-cyclotomic interpretation loses no coefficient information. -/
theorem executableToCyclotomic_injective (q exponent : ℕ) :
    Function.Injective (executableToCyclotomic q exponent) :=
  (quotientEquivCyclotomic exponent).injective.comp
    (quotientOf_injective (q := q) (Nat.two_pow_pos exponent))

/-- Over a nontrivial coefficient ring, every class in the power-of-two cyclotomic quotient has
an executable degree-`2^k` coefficient representative. -/
theorem executableToCyclotomic_surjective (q exponent : ℕ) [Nontrivial (ZMod q)] :
    Function.Surjective (executableToCyclotomic q exponent) :=
  (quotientEquivCyclotomic exponent).surjective.comp
    (quotientOf_surjective (q := q) (Nat.two_pow_pos exponent))

/-- The executable coefficient carrier and the power-of-two cyclotomic quotient are in
bijection. -/
theorem executableToCyclotomic_bijective (q exponent : ℕ) [Nontrivial (ZMod q)] :
    Function.Bijective (executableToCyclotomic q exponent) :=
  ⟨executableToCyclotomic_injective q exponent,
    executableToCyclotomic_surjective q exponent⟩

/-- Carrier equivalence between executable negacyclic polynomials and their exact cyclotomic
quotient.  Multiplication preservation is recorded separately below. -/
noncomputable def executableEquivCyclotomic (q exponent : ℕ) [Nontrivial (ZMod q)] :
    Rq q (2 ^ exponent) ≃
      CyclotomicQuotient (ZMod q) (2 ^ (exponent + 1)) :=
  Equiv.ofBijective (executableToCyclotomic q exponent)
    (executableToCyclotomic_bijective q exponent)

/-- Executable zero agrees with zero in the power-of-two cyclotomic quotient. -/
theorem executableToCyclotomic_zero (q exponent : ℕ) :
    executableToCyclotomic q exponent (0 : Rq q (2 ^ exponent)) = 0 := by
  unfold executableToCyclotomic
  rw [quotientOf_zero]
  exact map_zero (quotientEquivCyclotomic exponent)

/-- Executable coefficientwise addition agrees with addition in the power-of-two cyclotomic
quotient. -/
theorem executableToCyclotomic_add (q exponent : ℕ)
    (left right : Rq q (2 ^ exponent)) :
    executableToCyclotomic q exponent (left + right) =
      executableToCyclotomic q exponent left +
        executableToCyclotomic q exponent right := by
  unfold executableToCyclotomic
  rw [quotientOf_add]
  exact map_add (quotientEquivCyclotomic exponent) _ _

/-- Executable negacyclic multiplication agrees with multiplication in the power-of-two
cyclotomic quotient. -/
theorem executableToCyclotomic_mul (q exponent : ℕ)
    (left right : Rq q (2 ^ exponent)) :
    executableToCyclotomic q exponent
        ((negacyclicRing q (2 ^ exponent)).mul left right) =
      executableToCyclotomic q exponent left *
        executableToCyclotomic q exponent right := by
  unfold executableToCyclotomic
  rw [quotientOf_mul]
  exact map_mul (quotientEquivCyclotomic exponent) _ _

/-- Semiring-notation form of `executableToCyclotomic_mul`. -/
theorem executableToCyclotomic_semiring_mul (q exponent : ℕ)
    (left right : Rq q (2 ^ exponent)) :
    executableToCyclotomic q exponent (left * right) =
      executableToCyclotomic q exponent left *
        executableToCyclotomic q exponent right := by
  change executableToCyclotomic q exponent
      ((negacyclicRing q (2 ^ exponent)).mul left right) = _
  exact executableToCyclotomic_mul q exponent left right

/-- The `CommRing` multiplication selected by generic matrix-LWE code is also preserved by the
cyclotomic interpretation. -/
theorem executableToCyclotomic_commRing_mul (q exponent : ℕ)
    (left right : Rq q (2 ^ exponent)) :
    executableToCyclotomic q exponent
        (@Mul.mul (Rq q (2 ^ exponent))
          (LatticeCrypto.vectorNegacyclicRing_instCommRing
            (ZMod q) (2 ^ exponent)).toMul left right) =
      executableToCyclotomic q exponent left *
        executableToCyclotomic q exponent right := by
  unfold executableToCyclotomic
  rw [quotientOf_commRing_mul]
  exact map_mul (quotientEquivCyclotomic exponent) _ _

end FormalProof4FHE.RLWE.PowerOfTwoCyclotomic
