/-
Copyright (c) 2026 Kotaro Matsuoka. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Kotaro Matsuoka
-/

import FormalProof4FHE.RLWE.RegularCoverSameKeyBGV
import FormalProof4FHE.RLWE.RingRegev

/-!
# Technical native-BGV instantiation of the regular cover

This module packages the secret-dependent rows and non-ring operations appearing in the
Geelen--Vercauteren BGV/BFV bootstrap implementation.  It proves that public-key, boot-key,
automorphism-switch, and relinearization messages all belong to the affine-automorphism span
handled by the regular-cover compiler.
-/

open BigOperators

namespace FormalProof4FHE.RLWE.BinaryNTTSecurity.RegularCoverBGVInstantiation

noncomputable section

/-- The four secret-dependent row kinds generated by the native BGV implementation. -/
inductive NativeKeyRow (Automorphism : Type) (R : Type)
  | publicKey
  | bootKey (weight : R)
  | switchKey (automorphism : Automorphism) (weight : R)
  | relinearizationKey (weight : R)

/-- Semantic plaintext carried by one native evaluation-key row. -/
def NativeKeyRow.message {Automorphism R : Type} [CommRing R]
    (sigma : Automorphism → R ≃+* R) (secret : R) :
    NativeKeyRow Automorphism R → R
  | .publicKey => 0
  | .bootKey weight => weight * secret
  | .switchKey automorphism weight => weight * sigma automorphism secret
  | .relinearizationKey weight => weight * secret ^ 2

/-- Public constant plus a public linear combination of automorphed secrets. -/
def InAffineAutomorphismSpan {Automorphism R : Type}
    [Fintype Automorphism] [CommRing R]
    (sigma : Automorphism → R ≃+* R) (secret message : R) : Prop :=
  ∃ (constant : R) (coefficients : Automorphism → R),
    message = constant + ∑ automorphism, coefficients automorphism * sigma automorphism secret

theorem zero_mem_affineSpan {Automorphism R : Type}
    [Fintype Automorphism] [CommRing R]
    (sigma : Automorphism → R ≃+* R) (secret : R) :
    InAffineAutomorphismSpan sigma secret 0 := by
  refine ⟨0, fun _ => 0, ?_⟩
  simp

theorem automorphism_mul_mem_affineSpan {Automorphism R : Type}
    [Fintype Automorphism] [DecidableEq Automorphism] [CommRing R]
    (sigma : Automorphism → R ≃+* R) (secret weight : R)
    (selected : Automorphism) :
    InAffineAutomorphismSpan sigma secret (weight * sigma selected secret) := by
  refine ⟨0, fun index => if index = selected then weight else 0, ?_⟩
  simp

/-- Exact coverage of every native public/evaluation-key message. -/
theorem nativeKeyRow_mem_affineSpan {Automorphism R : Type}
    [Fintype Automorphism] [DecidableEq Automorphism] [CommRing R]
    (sigma : Automorphism → R ≃+* R) (identity : Automorphism)
    (hidentity : sigma identity = RingEquiv.refl R)
    (secret u v : R) (hquadratic : secret ^ 2 = u * secret + v)
    (row : NativeKeyRow Automorphism R) :
    InAffineAutomorphismSpan sigma secret (row.message sigma secret) := by
  cases row with
  | publicKey => exact zero_mem_affineSpan sigma secret
  | bootKey weight =>
      simpa [NativeKeyRow.message, hidentity] using
        (automorphism_mul_mem_affineSpan sigma secret weight identity)
  | switchKey automorphism weight =>
      exact automorphism_mul_mem_affineSpan sigma secret weight automorphism
  | relinearizationKey weight =>
      refine ⟨weight * v,
        fun index => if index = identity then weight * u else 0, ?_⟩
      simp only [NativeKeyRow.message, hquadratic]
      simp [hidentity]
      ring

/-- A complete finite table of native key rows is pointwise covered by one compiler family. -/
theorem nativeKeyTable_mem_affineSpan {Row Automorphism R : Type}
    [Fintype Automorphism] [DecidableEq Automorphism] [CommRing R]
    (sigma : Automorphism → R ≃+* R) (identity : Automorphism)
    (hidentity : sigma identity = RingEquiv.refl R)
    (secret u v : R) (hquadratic : secret ^ 2 = u * secret + v)
    (rows : Row → NativeKeyRow Automorphism R) :
    ∀ row, InAffineAutomorphismSpan sigma secret ((rows row).message sigma secret) :=
  fun row => nativeKeyRow_mem_affineSpan sigma identity hidentity secret u v hquadratic (rows row)

/-! ## Componentwise lifting of rounding and modulus operations -/

/-- Lift an arbitrary base operation independently to every cover component. -/
def pointwiseMap {GroupIndex R S : Type} (operation : R → S)
    (value : RegularCoverSameKeyBGV.Cover GroupIndex R) :
    RegularCoverSameKeyBGV.Cover GroupIndex S :=
  fun coordinate => operation (value coordinate)

@[simp]
theorem pointwiseMap_diagonal {GroupIndex R S : Type}
    (operation : R → S) (value : R) :
    pointwiseMap (GroupIndex := GroupIndex) operation
        (RegularCoverSameKeyBGV.diagonal value) =
      RegularCoverSameKeyBGV.diagonal (operation value) := by
  rfl

theorem pointwiseMap_comp {GroupIndex R S T : Type}
    (outer : S → T) (inner : R → S)
    (value : RegularCoverSameKeyBGV.Cover GroupIndex R) :
    pointwiseMap outer (pointwiseMap inner value) =
      pointwiseMap (outer ∘ inner) value := by
  rfl

/-- Compatibility required of centered reduction, modulus reduction, or another non-ring base
operation with the selected automorphism action. -/
def EquivariantMap {GroupIndex R S : Type} [Group GroupIndex]
    [CommRing R] [CommRing S]
    (sourceAction : GroupIndex →* R ≃+* R)
    (targetAction : GroupIndex →* S ≃+* S)
    (operation : R → S) : Prop :=
  ∀ element value,
    operation (sourceAction element value) = targetAction element (operation value)

/-- Every equivariant componentwise operation commutes with the lifted regular action. -/
theorem pointwiseMap_liftedAction {GroupIndex R S : Type}
    [Group GroupIndex] [CommRing R] [CommRing S]
    (sourceAction : GroupIndex →* R ≃+* R)
    (targetAction : GroupIndex →* S ≃+* S)
    (operation : R → S)
    (hequivariant : EquivariantMap sourceAction targetAction operation)
    (element : GroupIndex)
    (value : RegularCoverSameKeyBGV.Cover GroupIndex R) :
    pointwiseMap operation
        (RegularCoverSameKeyBGV.liftedAction sourceAction element value) =
      RegularCoverSameKeyBGV.liftedAction targetAction element
        (pointwiseMap operation value) := by
  funext coordinate
  exact hequivariant element (value (element⁻¹ * coordinate))

/-- Signed coefficient permutation used by power-of-two cyclotomic automorphisms. -/
def signedPermute {Coefficient Source : Type} [Neg Coefficient]
    (permutation : Equiv.Perm Source) (negated : Source → Bool)
    (value : Source → Coefficient) : Source → Coefficient :=
  fun coordinate =>
    if negated coordinate then -value (permutation coordinate)
    else value (permutation coordinate)

/-- Apply one scalar rounding or modulus operation independently to every coefficient. -/
def coefficientwise {Source Coefficient Target : Type}
    (operation : Coefficient → Target) (value : Source → Coefficient) : Source → Target :=
  fun coordinate => operation (value coordinate)

/-- Every odd scalar operation commutes with every signed coefficient permutation.  This is the
technical condition used by centered reduction and signed-permutation cyclotomic automorphisms. -/
theorem coefficientwise_signedPermute
    {Source Coefficient Target : Type} [Neg Coefficient] [Neg Target]
    (operation : Coefficient → Target)
    (hneg : ∀ value, operation (-value) = -operation value)
    (permutation : Equiv.Perm Source) (negated : Source → Bool)
    (value : Source → Coefficient) :
    coefficientwise operation (signedPermute permutation negated value) =
      signedPermute permutation negated (coefficientwise operation value) := by
  funext coordinate
  by_cases hsign : negated coordinate
  · simp [coefficientwise, signedPermute, hsign, hneg]
  · simp [coefficientwise, signedPermute, hsign]

/-- Unsigned coefficientwise operations commute with coefficient permutations without any
algebraic premise. -/
theorem coefficientwise_permute
    {Source Coefficient Target : Type}
    (operation : Coefficient → Target) (permutation : Equiv.Perm Source)
    (value : Source → Coefficient) :
    coefficientwise operation (fun coordinate => value (permutation coordinate)) =
      fun coordinate => coefficientwise operation value (permutation coordinate) := by
  rfl

/-- Cover reduction induced by a base ring homomorphism. -/
def coverRingHom {GroupIndex R S : Type} [Semiring R] [Semiring S]
    (hom : R →+* S) :
    RegularCoverSameKeyBGV.Cover GroupIndex R →+*
      RegularCoverSameKeyBGV.Cover GroupIndex S where
  toFun := pointwiseMap hom
  map_one' := by funext coordinate; simp [pointwiseMap]
  map_mul' left right := by funext coordinate; simp [pointwiseMap]
  map_zero' := by funext coordinate; simp [pointwiseMap]
  map_add' left right := by funext coordinate; simp [pointwiseMap]

theorem coverRingHom_diagonal {GroupIndex R S : Type}
    [Semiring R] [Semiring S] (hom : R →+* S) (value : R) :
    coverRingHom (GroupIndex := GroupIndex) hom
        (RegularCoverSameKeyBGV.diagonal value) =
      RegularCoverSameKeyBGV.diagonal (hom value) := by
  rfl

/-! ## Cover correctness bounds -/

/-- Coordinatewise cover bound, avoiding any extra factor equal to the number of components. -/
def CoverBound {GroupIndex R : Type} (size : R → ℝ)
    (bound : ℝ) (value : RegularCoverSameKeyBGV.Cover GroupIndex R) : Prop :=
  ∀ coordinate, size (value coordinate) ≤ bound

theorem CoverBound.add {GroupIndex R : Type} [Add R]
    (size : R → ℝ) (leftBound rightBound : ℝ)
    (hadd : ∀ left right, size (left + right) ≤ size left + size right)
    {left right : RegularCoverSameKeyBGV.Cover GroupIndex R}
    (hleft : CoverBound size leftBound left)
    (hright : CoverBound size rightBound right) :
    CoverBound size (leftBound + rightBound) (left + right) := by
  intro coordinate
  exact (hadd _ _).trans (add_le_add (hleft coordinate) (hright coordinate))

theorem CoverBound.mul {GroupIndex R : Type} [Mul R]
    (size : R → ℝ) (expansion leftBound rightBound : ℝ)
    (hexpansion_nonneg : 0 ≤ expansion)
    (hmul : ∀ left right, size (left * right) ≤ expansion * size left * size right)
    {left right : RegularCoverSameKeyBGV.Cover GroupIndex R}
    (hleft : CoverBound size leftBound left)
    (hright : CoverBound size rightBound right)
    (hsize_nonneg : ∀ value, 0 ≤ size value)
    (hleft_nonneg : 0 ≤ leftBound) :
    CoverBound size (expansion * leftBound * rightBound) (left * right) := by
  intro coordinate
  refine (hmul _ _).trans ?_
  exact mul_le_mul
    (mul_le_mul_of_nonneg_left (hleft coordinate) hexpansion_nonneg)
    (hright coordinate) (hsize_nonneg _) (mul_nonneg hexpansion_nonneg hleft_nonneg)

/-- A lifted automorphism preserves the same cover bound when every base automorphism preserves
the base size exactly. -/
theorem CoverBound.liftedAction {GroupIndex R : Type}
    [Group GroupIndex] [CommRing R]
    (action : GroupIndex →* R ≃+* R) (size : R → ℝ)
    (haction : ∀ element value, size (action element value) = size value)
    (bound : ℝ) (value : RegularCoverSameKeyBGV.Cover GroupIndex R)
    (hvalue : CoverBound size bound value) (element : GroupIndex) :
    CoverBound size bound
      (RegularCoverSameKeyBGV.liftedAction action element value) := by
  intro coordinate
  change size (action element (value (element⁻¹ * coordinate))) ≤ bound
  rw [haction]
  exact hvalue _

/-- A base-operation bound transfers componentwise with no cover-size multiplier. -/
theorem CoverBound.pointwiseMap {GroupIndex R S : Type}
    (sourceSize : R → ℝ) (targetSize : S → ℝ)
    (sourceBound targetBound : ℝ) (operation : R → S)
    (hoperation : ∀ value, sourceSize value ≤ sourceBound →
      targetSize (operation value) ≤ targetBound)
    (value : RegularCoverSameKeyBGV.Cover GroupIndex R)
    (hvalue : CoverBound sourceSize sourceBound value) :
    CoverBound targetSize targetBound (pointwiseMap operation value) := by
  intro coordinate
  exact hoperation _ (hvalue coordinate)

/-! ## Pivot advantage accounting -/

/-- Finite arithmetic certificate for rejection-sampled pivot reductions. -/
structure PivotAdvantageCertificate where
  targetAdvantage : ℝ
  sourceAdvantage : ℝ
  successProbability : ℝ
  target_nonneg : 0 ≤ targetAdvantage
  success_pos : 0 < successProbability
  source_eq : sourceAdvantage = successProbability * targetAdvantage

theorem PivotAdvantageCertificate.target_le_div_source
    (certificate : PivotAdvantageCertificate) :
    certificate.targetAdvantage ≤
      certificate.sourceAdvantage / certificate.successProbability := by
  rw [certificate.source_eq]
  apply le_of_eq
  field_simp [certificate.success_pos.ne']

theorem PivotAdvantageCertificate.target_le_source_div_one_sub
    (certificate : PivotAdvantageCertificate) (failure : ℝ)
    (_hfailure : 0 ≤ failure)
    (hsuccess : 1 - failure ≤ certificate.successProbability)
    (hfailure_lt : failure < 1) :
    certificate.targetAdvantage ≤ certificate.sourceAdvantage / (1 - failure) := by
  rw [certificate.source_eq]
  have hdenom : 0 < 1 - failure := by linarith
  rw [le_div_iff₀ hdenom]
  nlinarith [certificate.target_nonneg]

/-! ## Explicit challenge-encryption hybrid -/

/-- Once the regular-cover compiler has replaced the complete public-key table by uniform rows,
dense-binary ring-Regev encryption over the cover has the repository's explicit leftover-hash
bound.  This is the proof-oriented replacement for the Magma implementation's sparse-ternary
ephemeral encryption. -/
theorem coverRingRegev_subsetHash_leftover
    {GroupIndex R : Type}
    [Fintype GroupIndex] [DecidableEq GroupIndex]
    [CommRing R] [Fintype R] [DecidableEq R] [SampleableType R]
    [SampleableType (RegularCoverSameKeyBGV.Cover GroupIndex R)]
    (sampleCount : ℕ) :
    tvDist
        (FormalProof4FHE.LeftoverHash.hashed
          (FormalProof4FHE.RingRegev.subsetHash
            (RegularCoverSameKeyBGV.Cover GroupIndex R) 1 sampleCount))
        (FormalProof4FHE.LeftoverHash.ideal
          (Seed := FormalProof4FHE.RingRegev.PublicKey
            (RegularCoverSameKeyBGV.Cover GroupIndex R) 1 sampleCount)
          (Output := FormalProof4FHE.RingRegev.Ciphertext
            (RegularCoverSameKeyBGV.Cover GroupIndex R) 1)) ≤
      Real.sqrt
          (Fintype.card
              (FormalProof4FHE.RingRegev.Ciphertext
                (RegularCoverSameKeyBGV.Cover GroupIndex R) 1) /
            Fintype.card (Fin sampleCount → Bool)) / 2 :=
  FormalProof4FHE.RingRegev.subsetHash_leftover
    (RegularCoverSameKeyBGV.Cover GroupIndex R) 1 sampleCount

theorem card_cover {GroupIndex R : Type}
    [Fintype GroupIndex] [DecidableEq GroupIndex] [Fintype R] :
    Fintype.card (RegularCoverSameKeyBGV.Cover GroupIndex R) =
      Fintype.card R ^ Fintype.card GroupIndex := by
  simp

/-- Explicit statistical term for rank-one cover encryption. -/
theorem coverRingRegev_subsetHash_leftover_explicit
    {GroupIndex R : Type}
    [Fintype GroupIndex] [DecidableEq GroupIndex]
    [CommRing R] [Fintype R] [DecidableEq R] [SampleableType R]
    [SampleableType (RegularCoverSameKeyBGV.Cover GroupIndex R)]
    (sampleCount : ℕ) :
    tvDist
        (FormalProof4FHE.LeftoverHash.hashed
          (FormalProof4FHE.RingRegev.subsetHash
            (RegularCoverSameKeyBGV.Cover GroupIndex R) 1 sampleCount))
        (FormalProof4FHE.LeftoverHash.ideal
          (Seed := FormalProof4FHE.RingRegev.PublicKey
            (RegularCoverSameKeyBGV.Cover GroupIndex R) 1 sampleCount)
          (Output := FormalProof4FHE.RingRegev.Ciphertext
            (RegularCoverSameKeyBGV.Cover GroupIndex R) 1)) ≤
      Real.sqrt
          (((Fintype.card R : ℝ) ^ (2 * Fintype.card GroupIndex)) /
            ((2 : ℝ) ^ sampleCount)) / 2 := by
  simpa [FormalProof4FHE.RingRegev.Ciphertext, card_cover,
    Fintype.card_fun, Fintype.card_prod, Nat.cast_pow, pow_mul,
    mul_comm] using
    (coverRingRegev_subsetHash_leftover
      (GroupIndex := GroupIndex) (R := R) sampleCount)

/-! ## End-to-end finite composition interfaces -/

/-- Security terms remaining after instantiating the exact compiler and dense-binary challenge
encryption.  No circular-security term occurs in this certificate. -/
structure EndToEndSecurityCertificate where
  indCpaAdvantage : ℝ
  transcriptAdvantage : ℝ
  pkeMaskingDistance : ℝ
  pivot : PivotAdvantageCertificate
  pivotFailure : ℝ
  indCpa_nonneg : 0 ≤ indCpaAdvantage
  transcript_nonneg : 0 ≤ transcriptAdvantage
  pke_nonneg : 0 ≤ pkeMaskingDistance
  pivotFailure_nonneg : 0 ≤ pivotFailure
  pivotFailure_lt_one : pivotFailure < 1
  transcript_le_pivot : transcriptAdvantage ≤ pivot.targetAdvantage
  indCpa_le : indCpaAdvantage ≤ transcriptAdvantage + pkeMaskingDistance
  pivot_success : 1 - pivotFailure ≤ pivot.successProbability

/-- Final finite security composition: ordinary-source advantage divided by pivot success, plus
the explicit public-key masking distance. -/
theorem EndToEndSecurityCertificate.indCpa_le_source_add_masking
    (certificate : EndToEndSecurityCertificate) :
    certificate.indCpaAdvantage ≤
      certificate.pivot.sourceAdvantage / (1 - certificate.pivotFailure) +
        certificate.pkeMaskingDistance := by
  have hpivot := certificate.pivot.target_le_source_div_one_sub
    certificate.pivotFailure certificate.pivotFailure_nonneg
    certificate.pivot_success certificate.pivotFailure_lt_one
  linarith [certificate.indCpa_le, certificate.transcript_le_pivot]

/-- Correctness data exported by one concrete native BGV bootstrap. -/
structure NativeRefreshCertificate where
  inputBound : ℝ
  freshBound : ℝ
  perComponentFailure : ℝ
  input_nonneg : 0 ≤ inputBound
  fresh_nonneg : 0 ≤ freshBound
  failure_nonneg : 0 ≤ perComponentFailure
  contraction : freshBound < inputBound

/-- Union-bound failure for one cover refresh. -/
def NativeRefreshCertificate.coverFailure
    (certificate : NativeRefreshCertificate) (componentCount : ℕ) : ℝ :=
  componentCount * certificate.perComponentFailure

/-- Reusing one fixed evaluation key for `refreshCount` public refreshes incurs only the ordinary
union bound; security itself is preserved by public post-processing. -/
theorem NativeRefreshCertificate.repeatedFailure_le
    (certificate : NativeRefreshCertificate)
    (componentCount refreshCount : ℕ)
    (singleExecutionFailure : ℝ)
    (hsingle : singleExecutionFailure ≤ certificate.coverFailure componentCount) :
    refreshCount * singleExecutionFailure ≤
      refreshCount * componentCount * certificate.perComponentFailure := by
  have hrefresh : (0 : ℝ) ≤ refreshCount := by positivity
  calc
    refreshCount * singleExecutionFailure ≤
        refreshCount * certificate.coverFailure componentCount :=
      mul_le_mul_of_nonneg_left hsingle hrefresh
    _ = _ := by simp [NativeRefreshCertificate.coverFailure]; ring

end

end FormalProof4FHE.RLWE.BinaryNTTSecurity.RegularCoverBGVInstantiation
