/-
Copyright (c) 2026 Kotaro Matsuoka. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Kotaro Matsuoka
-/

import FormalProof4FHE.Probability.FiniteSurjectiveFiber
import FormalProof4FHE.TFHE.NativeDiagonalUnitTwoColumnSlice
import FormalProof4FHE.TFHE.NativePowerOfTwoLocalRing

/-!
# Binary Dependence of the Bad Two-Column Event

For a native power-of-two TFHE ring, parity evaluation is the residue-field map to `ZMod 2`.
Once the selected source-error coordinate is a unit, every selected/pivot minor is nonunit exactly
when the parity vector of the proposed kernel value lies on the binary line generated by the
source-error parity vector.  That line has two elements.  Surjectivity of coordinatewise parity
evaluation then gives an exact finite count of the bad vectors.
-/

open Matrix OracleComp
open scoped BigOperators

namespace FormalProof4FHE.TFHE.Native.ShiftedCandidateEvaluator.DiagonalNormalForm

noncomputable section

open FormalProof4FHE.TFHE

attribute [local instance] NoiseBounds.positiveRqCommRing NoiseBounds.positiveRqRing

/-! ## Residue-field form of the retained minor -/

/-- Candidate-dependent negation disappears after mapping to the binary residue field. -/
@[simp]
theorem rqParityEval_signedValue
    {q ringDegree : ℕ} (heven : 2 ∣ q) (hdegree : 0 < ringDegree)
    (candidate : Bool) (value : RLWE.Rq q ringDegree) :
    rqParityEval heven hdegree (signedValue candidate value) =
      rqParityEval heven hdegree value := by
  cases candidate <;> simp [signedValue, ZMod.neg_eq_self_mod_two]

/-- The selected/pivot determinant after binary parity evaluation. -/
def retainedParityColumnMinor
    {q degree ringRank levels : ℕ} [NeZero q]
    (heven : 2 ∣ q)
    (sourceError value :
      Fin (TGSW.rowCount ringRank levels) → RLWE.Rq q (degree + 1))
    (selected pivot : DifferenceDigitColumn ringRank levels) : ZMod 2 :=
  rqParityEval heven (Nat.succ_pos degree)
        (sourceError (finProdFinEquiv selected)) *
      rqParityEval heven (Nat.succ_pos degree)
        (value (finProdFinEquiv pivot)) -
    rqParityEval heven (Nat.succ_pos degree)
        (sourceError (finProdFinEquiv pivot)) *
      rqParityEval heven (Nat.succ_pos degree)
        (value (finProdFinEquiv selected))

/-- Parity evaluation maps the native retained minor to its explicit binary determinant. -/
theorem rqParityEval_retainedKernelColumnMinor
    {q degree ringRank levels : ℕ} [NeZero q]
    (heven : 2 ∣ q) (candidate : Bool)
    (sourceError value :
      Fin (TGSW.rowCount ringRank levels) → RLWE.Rq q (degree + 1))
    (selected pivot : DifferenceDigitColumn ringRank levels) :
    rqParityEval heven (Nat.succ_pos degree)
        (retainedKernelColumnMinor candidate sourceError value selected pivot) =
      retainedParityColumnMinor heven sourceError value selected pivot := by
  simp [retainedKernelColumnMinor, retainedParityColumnMinor, map_sub, map_mul]

/-- When parity evaluation reflects units, a retained minor is a unit exactly when its binary
determinant is nonzero. -/
theorem isUnit_retainedKernelColumnMinor_iff_parity_ne_zero
    {q degree ringRank levels : ℕ} [NeZero q]
    (heven : 2 ∣ q) (candidate : Bool)
    (sourceError value :
      Fin (TGSW.rowCount ringRank levels) → RLWE.Rq q (degree + 1))
    (selected pivot : DifferenceDigitColumn ringRank levels)
    (localParity : IsLocalHom (rqParityEval heven (Nat.succ_pos degree))) :
    IsUnit (retainedKernelColumnMinor candidate sourceError value selected pivot) ↔
      retainedParityColumnMinor heven sourceError value selected pivot ≠ 0 := by
  rw [← rqParityEval_retainedKernelColumnMinor]
  constructor
  · intro hunit
    exact isUnit_iff_ne_zero.mp
      (hunit.map (rqParityEval heven (Nat.succ_pos degree)))
  · intro hnonzero
    letI : IsLocalHom (rqParityEval heven (Nat.succ_pos degree)) := localParity
    exact IsUnit.of_map (rqParityEval heven (Nat.succ_pos degree)) _
      (isUnit_iff_ne_zero.mpr hnonzero)

/-! ## The binary line generated by the source-error parity vector -/

/-- Coordinatewise parity evaluation as an additive homomorphism. -/
noncomputable def rqParityVectorAddHom
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q) :
    (Fin count → RLWE.Rq q (degree + 1)) →+ (Fin count → ZMod 2) where
  toFun value := fun row ↦ rqParityEval heven (Nat.succ_pos degree) (value row)
  map_zero' := by
    funext row
    exact map_zero (rqParityEval heven (Nat.succ_pos degree))
  map_add' left right := by
    funext row
    exact map_add (rqParityEval heven (Nat.succ_pos degree)) (left row) (right row)

@[simp]
theorem rqParityVectorAddHom_apply
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (value : Fin count → RLWE.Rq q (degree + 1)) (row : Fin count) :
    rqParityVectorAddHom heven value row =
      rqParityEval heven (Nat.succ_pos degree) (value row) := rfl

/-- Coordinatewise parity evaluation is surjective because scalar parity evaluation is. -/
theorem rqParityVectorAddHom_surjective
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q) :
    Function.Surjective (rqParityVectorAddHom heven :
      (Fin count → RLWE.Rq q (degree + 1)) →+ (Fin count → ZMod 2)) := by
  intro target
  have hscalar : Function.Surjective (rqParityEval heven (Nat.succ_pos degree)) :=
    ZMod.ringHom_surjective (rqParityEval heven (Nat.succ_pos degree))
  choose preimage hpreimage using fun row ↦ hscalar (target row)
  exact ⟨preimage, funext hpreimage⟩

/-- The binary scalar line generated by a source-error parity vector. -/
def sourceParityLine
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) (scalar : ZMod 2) :
    Fin count → ZMod 2 :=
  fun row ↦ scalar * rqParityEval heven (Nat.succ_pos degree) (sourceError row)

/-- The two possible binary scalar multiples of the source-error parity vector. -/
def sourceParitySpanFinset
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) :
    Finset (Fin count → ZMod 2) :=
  Finset.univ.image (sourceParityLine heven sourceError)

/-- A value is bad for every two-column slice exactly when its binary parity vector lies on the
source-error line. -/
abbrev RetainedParityDependent
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError value : Fin count → RLWE.Rq q (degree + 1)) : Prop :=
  rqParityVectorAddHom heven value ∈ sourceParitySpanFinset heven sourceError

/-- A unit source coordinate makes the source parity vector nonzero at that coordinate. -/
theorem rqParityEval_ne_zero_of_isUnit
    {q ringDegree : ℕ} (heven : 2 ∣ q) (hdegree : 0 < ringDegree)
    {value : RLWE.Rq q ringDegree} (hunit : IsUnit value) :
    rqParityEval heven hdegree value ≠ 0 := by
  exact isUnit_iff_ne_zero.mp (hunit.map (rqParityEval heven hdegree))

/-- A nonzero source coordinate makes binary scalar multiplication by the complete source parity
vector injective. -/
theorem sourceParityLine_injective_of_ne_zero
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) (selected : Fin count)
    (hselected : rqParityEval heven (Nat.succ_pos degree) (sourceError selected) ≠ 0) :
    Function.Injective (sourceParityLine heven sourceError) := by
  intro left right heq
  have hcoordinate := congrFun heq selected
  unfold sourceParityLine at hcoordinate
  exact mul_right_cancel₀ hselected hcoordinate

/-- Under the selected-unit condition the source parity span contains exactly two vectors. -/
theorem card_sourceParitySpanFinset_eq_two_of_isUnit
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) (selected : Fin count)
    (hunit : IsUnit (sourceError selected)) :
    (sourceParitySpanFinset heven sourceError).card = 2 := by
  unfold sourceParitySpanFinset
  rw [Finset.card_image_of_injective Finset.univ
    (sourceParityLine_injective_of_ne_zero heven sourceError selected
      (rqParityEval_ne_zero_of_isUnit heven (Nat.succ_pos degree) hunit))]
  simp

/-! ## Exact no-unit-minor characterization and count -/

/-- Every retained two-column minor is nonunit exactly when the proposed value has parity on the
binary source line. -/
theorem no_isUnit_retainedKernelColumnMinor_iff_parityDependent
    {q degree ringRank levels : ℕ} [NeZero q]
    (heven : 2 ∣ q) (candidate : Bool)
    (sourceError value :
      Fin (TGSW.rowCount ringRank levels) → RLWE.Rq q (degree + 1))
    (selected : DifferenceDigitColumn ringRank levels)
    (hunit : IsUnit (sourceError (finProdFinEquiv selected)))
    (localParity : IsLocalHom (rqParityEval heven (Nat.succ_pos degree))) :
    (¬ ∃ pivot : DifferenceDigitColumn ringRank levels,
        pivot ≠ selected ∧
          IsUnit (retainedKernelColumnMinor candidate sourceError value selected pivot)) ↔
      RetainedParityDependent heven sourceError value := by
  classical
  let selectedRow := finProdFinEquiv selected
  let sourceSelected := rqParityEval heven (Nat.succ_pos degree) (sourceError selectedRow)
  let valueSelected := rqParityEval heven (Nat.succ_pos degree) (value selectedRow)
  have hsourceSelected : sourceSelected ≠ 0 := by
    exact rqParityEval_ne_zero_of_isUnit heven (Nat.succ_pos degree) hunit
  constructor
  · intro hnone
    apply Finset.mem_image.mpr
    refine ⟨valueSelected * sourceSelected⁻¹, Finset.mem_univ _, ?_⟩
    funext row
    obtain ⟨pivot, rfl⟩ := finProdFinEquiv.surjective row
    by_cases hpivot : pivot = selected
    · subst pivot
      symm
      change valueSelected =
        sourceParityLine heven sourceError
          (valueSelected * sourceSelected⁻¹) selectedRow
      unfold sourceParityLine
      change valueSelected = (valueSelected * sourceSelected⁻¹) * sourceSelected
      calc
        valueSelected = valueSelected * 1 := by rw [mul_one]
        _ = valueSelected * (sourceSelected⁻¹ * sourceSelected) := by
          rw [inv_mul_cancel₀ hsourceSelected]
        _ = (valueSelected * sourceSelected⁻¹) * sourceSelected := by ring
    · have hnotUnit :
          ¬ IsUnit (retainedKernelColumnMinor candidate sourceError value selected pivot) := by
        intro hpivotUnit
        exact hnone ⟨pivot, hpivot, hpivotUnit⟩
      have hzero : retainedParityColumnMinor heven sourceError value selected pivot = 0 := by
        by_contra hne
        exact hnotUnit
          ((isUnit_retainedKernelColumnMinor_iff_parity_ne_zero heven candidate
            sourceError value selected pivot localParity).mpr hne)
      have hequation :
          sourceSelected * rqParityEval heven (Nat.succ_pos degree)
              (value (finProdFinEquiv pivot)) =
            rqParityEval heven (Nat.succ_pos degree)
                (sourceError (finProdFinEquiv pivot)) * valueSelected := by
        exact sub_eq_zero.mp hzero
      symm
      change rqParityEval heven (Nat.succ_pos degree)
          (value (finProdFinEquiv pivot)) =
        (valueSelected * sourceSelected⁻¹) *
          rqParityEval heven (Nat.succ_pos degree)
            (sourceError (finProdFinEquiv pivot))
      calc
        rqParityEval heven (Nat.succ_pos degree)
            (value (finProdFinEquiv pivot)) =
            1 * rqParityEval heven (Nat.succ_pos degree)
              (value (finProdFinEquiv pivot)) := by rw [one_mul]
        _ = (sourceSelected⁻¹ * sourceSelected) *
              rqParityEval heven (Nat.succ_pos degree)
                (value (finProdFinEquiv pivot)) := by
          rw [inv_mul_cancel₀ hsourceSelected]
        _ = sourceSelected⁻¹ *
            (sourceSelected * rqParityEval heven (Nat.succ_pos degree)
              (value (finProdFinEquiv pivot))) := by ring
        _ = sourceSelected⁻¹ *
            (rqParityEval heven (Nat.succ_pos degree)
                (sourceError (finProdFinEquiv pivot)) * valueSelected) := by
          rw [hequation]
        _ = (valueSelected * sourceSelected⁻¹) *
            rqParityEval heven (Nat.succ_pos degree)
              (sourceError (finProdFinEquiv pivot)) := by ring
  · intro hdependent hexists
    obtain ⟨pivot, hpivot, hpivotUnit⟩ := hexists
    obtain ⟨scalar, _, hline⟩ := Finset.mem_image.mp hdependent
    have hselectedLine := congrFun hline (finProdFinEquiv selected)
    have hpivotLine := congrFun hline (finProdFinEquiv pivot)
    change scalar * rqParityEval heven (Nat.succ_pos degree)
        (sourceError (finProdFinEquiv selected)) =
      rqParityEval heven (Nat.succ_pos degree)
        (value (finProdFinEquiv selected)) at hselectedLine
    change scalar * rqParityEval heven (Nat.succ_pos degree)
        (sourceError (finProdFinEquiv pivot)) =
      rqParityEval heven (Nat.succ_pos degree)
        (value (finProdFinEquiv pivot)) at hpivotLine
    have hparityZero :
        retainedParityColumnMinor heven sourceError value selected pivot = 0 := by
      unfold retainedParityColumnMinor
      rw [← hselectedLine, ← hpivotLine]
      ring
    have hparityNe :=
      (isUnit_retainedKernelColumnMinor_iff_parity_ne_zero heven candidate
        sourceError value selected pivot localParity).mp hpivotUnit
    exact hparityNe hparityZero

/-- Exact bad-vector cardinality: two residue-field fibers, one for each scalar multiple of the
source parity vector. -/
theorem card_retainedParityDependent_eq_two_mul_zeroFiber
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) (selected : Fin count)
    (hunit : IsUnit (sourceError selected)) :
    (Finset.univ.filter fun value : Fin count → RLWE.Rq q (degree + 1) ↦
        RetainedParityDependent heven sourceError value).card =
      2 *
        (Finset.univ.filter fun value : Fin count → RLWE.Rq q (degree + 1) ↦
          rqParityVectorAddHom heven value = 0).card := by
  rw [FormalProof4FHE.FiniteSurjectiveFiber.card_preimage_finset_eq_card_mul_zeroFiber
    (rqParityVectorAddHom heven)
    (rqParityVectorAddHom_surjective heven)
    (sourceParitySpanFinset heven sourceError)]
  rw [card_sourceParitySpanFinset_eq_two_of_isUnit heven sourceError selected hunit]

/-- Exact size relation for the kernel of coordinatewise parity evaluation. -/
theorem rqParityVector_zeroFiberCard_mul_two_pow_eq_card
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q) :
    (Finset.univ.filter fun value : Fin count → RLWE.Rq q (degree + 1) ↦
        rqParityVectorAddHom heven value = 0).card * 2 ^ count =
      Fintype.card (Fin count → RLWE.Rq q (degree + 1)) := by
  simpa only [Fintype.card_fun, Fintype.card_fin, ZMod.card] using
    (FormalProof4FHE.FiniteSurjectiveFiber.zeroFiberCard_mul_card_eq_card_of_surjective
      (rqParityVectorAddHom heven)
      (rqParityVectorAddHom_surjective heven))

/-- A uniformly ranged native value is parity-dependent with exact density `2 / 2^count`, stated
without division as an integral cardinality identity. -/
theorem card_retainedParityDependent_mul_two_pow_eq_two_mul_card
    {q degree count : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) (selected : Fin count)
    (hunit : IsUnit (sourceError selected)) :
    (Finset.univ.filter fun value : Fin count → RLWE.Rq q (degree + 1) ↦
        RetainedParityDependent heven sourceError value).card * 2 ^ count =
      2 * Fintype.card (Fin count → RLWE.Rq q (degree + 1)) := by
  rw [card_retainedParityDependent_eq_two_mul_zeroFiber heven sourceError selected hunit]
  rw [Nat.mul_assoc, rqParityVector_zeroFiberCard_mul_two_pow_eq_card heven]

/-! ## Simultaneous tuples -/

/-- Every value in a simultaneous kernel tuple lies on the same binary source line. -/
abbrev RetainedParityDependentTuple
    {q degree count moment : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1))
    (values : Fin moment → (Fin count → RLWE.Rq q (degree + 1))) : Prop :=
  ∀ index, RetainedParityDependent heven sourceError (values index)

/-- Pointwise dependent tuples are exactly functions into the dependent-value subtype. -/
def retainedParityDependentTupleEquiv
    {q degree count moment : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) :
    {values : Fin moment → (Fin count → RLWE.Rq q (degree + 1)) //
        RetainedParityDependentTuple heven sourceError values} ≃
      (Fin moment →
        {value : Fin count → RLWE.Rq q (degree + 1) //
          RetainedParityDependent heven sourceError value}) where
  toFun values index := ⟨values.1 index, values.2 index⟩
  invFun values := ⟨fun index ↦ (values index).1, fun index ↦ (values index).2⟩
  left_inv values := by
    apply Subtype.ext
    rfl
  right_inv values := by
    funext index
    apply Subtype.ext
    rfl

/-- The bad simultaneous tuples are the Cartesian power of the bad single-value set. -/
theorem card_retainedParityDependentTuple_eq_pow
    {q degree count moment : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) :
    (Finset.univ.filter fun values :
        Fin moment → (Fin count → RLWE.Rq q (degree + 1)) ↦
      RetainedParityDependentTuple heven sourceError values).card =
      (Finset.univ.filter fun value : Fin count → RLWE.Rq q (degree + 1) ↦
        RetainedParityDependent heven sourceError value).card ^ moment := by
  classical
  rw [show
      (Finset.univ.filter fun values :
          Fin moment → (Fin count → RLWE.Rq q (degree + 1)) ↦
        RetainedParityDependentTuple heven sourceError values).card =
        Fintype.card
          {values : Fin moment → (Fin count → RLWE.Rq q (degree + 1)) //
            RetainedParityDependentTuple heven sourceError values} by
      symm
      apply Fintype.card_of_subtype
      intro values
      simp]
  rw [Fintype.card_congr (retainedParityDependentTupleEquiv heven sourceError)]
  rw [Fintype.card_fun, Fintype.card_fin]
  congr 1
  apply Fintype.card_of_subtype
  intro value
  simp

/-- Exact uniform-density identity for simultaneous bad tuples.  Each additional value supplies
another factor `2 / 2^count`. -/
theorem card_retainedParityDependentTuple_mul_two_pow_eq
    {q degree count moment : ℕ} [NeZero q] (heven : 2 ∣ q)
    (sourceError : Fin count → RLWE.Rq q (degree + 1)) (selected : Fin count)
    (hunit : IsUnit (sourceError selected)) :
    (Finset.univ.filter fun values :
        Fin moment → (Fin count → RLWE.Rq q (degree + 1)) ↦
      RetainedParityDependentTuple heven sourceError values).card *
        (2 ^ count) ^ moment =
      (2 * Fintype.card (Fin count → RLWE.Rq q (degree + 1))) ^ moment := by
  rw [card_retainedParityDependentTuple_eq_pow heven sourceError]
  rw [← mul_pow]
  rw [card_retainedParityDependent_mul_two_pow_eq_two_mul_card
    heven sourceError selected hunit]

/-- The complement of the simultaneous unit-minor event is exactly pointwise binary dependence. -/
theorem no_exists_isUnitMinor_tuple_iff_parityDependentTuple
    {q degree ringRank levels moment : ℕ} [NeZero q]
    (heven : 2 ∣ q) (candidate : Bool)
    (sourceError :
      Fin (TGSW.rowCount ringRank levels) → RLWE.Rq q (degree + 1))
    (selected : DifferenceDigitColumn ringRank levels)
    (hunit : IsUnit (sourceError (finProdFinEquiv selected)))
    (localParity : IsLocalHom (rqParityEval heven (Nat.succ_pos degree)))
    (values : Fin moment →
      (Fin (TGSW.rowCount ringRank levels) → RLWE.Rq q (degree + 1))) :
    (¬ ∃ index : Fin moment, ∃ pivot : DifferenceDigitColumn ringRank levels,
        pivot ≠ selected ∧
          IsUnit (retainedKernelColumnMinor candidate sourceError (values index)
            selected pivot)) ↔
      RetainedParityDependentTuple heven sourceError values := by
  constructor
  · intro hnone index
    apply (no_isUnit_retainedKernelColumnMinor_iff_parityDependent heven candidate
      sourceError (values index) selected hunit localParity).mp
    intro hexists
    exact hnone ⟨index, hexists⟩
  · intro hdependent hexists
    obtain ⟨index, pivot, hpivot, hminor⟩ := hexists
    have hnone :=
      (no_isUnit_retainedKernelColumnMinor_iff_parityDependent heven candidate
        sourceError (values index) selected hunit localParity).mpr (hdependent index)
    exact hnone ⟨pivot, hpivot, hminor⟩

end

end FormalProof4FHE.TFHE.Native.ShiftedCandidateEvaluator.DiagonalNormalForm
